'use strict';
(() => {
  pageNames.cloud='Konto og Cloud';
  const nav=document.querySelector('nav'),navButton=document.createElement('button');navButton.dataset.page='cloud';navButton.textContent='☁ Konto og Cloud';nav.append(navButton);
  const accountButton=document.createElement('button');accountButton.className='secondary';accountButton.id='cloud-account-button';accountButton.textContent='Logg inn';document.querySelector('.header-actions').append(accountButton);
  const section=document.createElement('section');section.id='page-cloud';section.className='page';
  section.innerHTML=`<style>
  #page-cloud [hidden]{display:none!important} #page-cloud .account-tabs{display:flex;gap:8px;margin:16px 0 24px}
  #page-cloud .account-tabs button[aria-pressed="true"]{background:#9ce4d1;color:#102033} #page-cloud .account-form{max-width:760px}
  #page-cloud .account-form label{display:block;margin:14px 0} #page-cloud .account-form input:not([type="checkbox"]){width:100%;margin-top:7px}
  #page-cloud .account-form small{display:block;margin-top:6px} #page-cloud .password-row{display:flex;gap:8px;align-items:center}
  #page-cloud .password-row input{flex:1;min-width:0} #page-cloud .account-status{border-left:3px solid #9ce4d1;padding:12px 16px;background:#152634;overflow-wrap:anywhere}
  #page-cloud .account-status.error{border-color:#ff9e9e;color:#ffd0d0} #page-cloud .server-setup{margin:20px 0;border:1px solid #30485a;border-radius:8px;padding:16px}
  #page-cloud .server-setup summary{cursor:pointer;font-weight:600} #page-cloud .account-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}
  </style>
  <div class="page-heading"><div><p class="eyebrow">EN KONTO FOR DIN RADIOHVERDAG</p><h1>Din HamNavigator-konto</h1><p>Opprett konto eller logg inn. HamNavigator kobler deg automatisk til Cloud.</p></div></div>
  <article class="card" id="cloud-auth-card"><div class="account-tabs" aria-label="Innlogging eller registrering"><button type="button" id="cloud-login-tab" class="secondary" aria-pressed="true">Logg inn</button><button type="button" id="cloud-register-tab" class="secondary" aria-pressed="false">Opprett konto</button></div>
  <form id="cloud-connect" class="account-form"><h2 id="cloud-auth-title">Velkommen tilbake</h2><p id="cloud-auth-intro">Bruk samme konto på enhetene dine.</p>
  <details class="server-setup" id="cloud-server-setup"><summary>Avansert: egen server</summary><p>Brukes bare hvis du har en annen privat Cloud-server.</p><button type="button" id="cloud-standard" class="secondary">Bruk HamNavigator Cloud</button>
  <button type="button" class="secondary" id="cloud-import">Åpne tilkoblingsfil</button><input type="file" id="cloud-connection-file" accept=".hamcloud" hidden>
  <label>Serveradresse<input name="url" type="url" required placeholder="https://servernavn:9443"></label><label>Sertifikatfil på denne PC-en<input name="certificate" placeholder="Fylles inn fra tilkoblingsfilen"><small>HamNavigator Cloud trenger ingen sertifikatfil.</small></label>
  <button type="button" class="secondary" id="cloud-check">Kontroller tilkobling</button><p id="cloud-connection-status" role="status"></p></details>
  <label>E-post<input name="email" type="email" required maxlength="232" autocomplete="username"></label>
  <label for="cloud-password">Passord</label><div class="password-row"><input id="cloud-password" name="password" type="password" required maxlength="256" aria-describedby="cloud-password-help" autocomplete="current-password"><button type="button" class="secondary" id="cloud-show-password" aria-pressed="false">Vis</button></div><small id="cloud-password-help"></small>
  <label id="cloud-confirm-label" hidden>Gjenta passord<input name="password_confirm" type="password" maxlength="256" autocomplete="new-password" disabled></label>
  <div id="cloud-verify-group" hidden><label>Kode fra e-posten<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{8}" maxlength="8" placeholder="8 sifre"></label><button type="button" id="cloud-resend" class="secondary">Send ny kode</button><p class="small muted">Koden gjelder i 15 minutter. Sjekk også søppelpost.</p></div><label id="cloud-invite-label" hidden>Invitasjonskode<input name="invite" autocomplete="off" disabled></label>
  <details id="cloud-recovery-details"><summary>Gjenoppretting etter passordbytte</summary><label>Gjenopprettingsnøkkel<input name="recovery" type="password" autocomplete="off" placeholder="Bare nødvendig hvis nøkkelen ikke finnes på denne PC-en"></label></details>
  <p id="cloud-register-info" class="small muted" hidden>Du får en engangskode på e-post for å bekrefte kontoen. Du velger selv når loggbok og innstillinger skal synkroniseres. Servereieren kan se kontoens e-post, appversjon og siste kontakt med appen for å vise hvem som er aktive. Ingen liste over tidligere aktivitet lagres.</p>
  <div class="account-actions"><button class="primary" id="cloud-submit">Logg inn</button><button type="button" class="text-button" id="cloud-forgot">Glemt passord?</button></div></form></article>
  <article class="card" id="cloud-reset-card" hidden><h2>Glemt passord</h2><p>Få en engangskode til kontoens e-postadresse og velg et nytt passord.</p><form id="cloud-reset-form" class="account-form">
    <label>E-post<input name="reset_email" type="email" required maxlength="232" autocomplete="username"></label><button type="button" id="cloud-reset-send" class="secondary">Send kode til e-post</button>
    <label>Kode fra e-posten<input name="reset_code" required pattern="[0-9]{8}" inputmode="numeric" autocomplete="one-time-code" maxlength="8"></label>
    <label>Nytt passord<input name="reset_password" type="password" required minlength="12" maxlength="256" autocomplete="new-password"><small>Minst 12 og maksimalt 256 tegn.</small></label>
    <label>Gjenta nytt passord<input name="reset_confirm" type="password" required minlength="12" maxlength="256" autocomplete="new-password"></label>
    <p class="small muted">På en ny PC kan gjenopprettingsnøkkelen din være nødvendig for å åpne de krypterte innstillingene etter passordbytte. Gamle innstillinger og kontakter beholdes.</p>
    <div class="account-actions"><button class="primary">Lagre nytt passord</button><button type="button" id="cloud-reset-cancel" class="secondary">Tilbake til innlogging</button></div></form></article>
  <p id="cloud-auth-status" class="account-status" role="status" aria-live="polite">Logg inn eller opprett konto for å bruke HamNavigator. Nedlasting er gratis og åpen.</p>
  <article class="card" id="cloud-account-card" hidden><p class="eyebrow">DIN KONTO</p><h2 id="cloud-account-email"></h2><p id="cloud-account-server"></p><button id="cloud-retry" class="secondary">Bekreft innlogging</button> <button id="cloud-out" class="secondary">Logg ut</button> <button id="cloud-recovery" class="secondary">Lagre gjenopprettingsnøkkel</button><p class="small muted">Nøkkelen gjenoppretter krypterte innstillinger hvis du glemmer kontopassordet. Oppbevar den privat. Utlogging beholder kontaktene på denne PC-en.</p></article>
  <article class="card"><h2>Synkronisering</h2><p id="cloud-status" role="status" aria-live="polite">Logg inn for å synkronisere.</p><label><input id="cloud-auto" type="checkbox" disabled> Automatisk synkronisering hvert 10. sekund</label><p><button id="cloud-now" class="primary" disabled>Synkroniser nå</button></p>
  <p class="small muted">Digital og MY SHACK bruker fellesloggen hamnavigator.adi. Kontakter deles begge veier. Digital-, Map- og MY SHACK-oppsett, passord og API-nøkler lagres kryptert i Cloud. Mottatte programinnstillinger tas i bruk ved neste oppstart. Radioens aktive sending gjenopptas ikke.</p>
  <p id="cloud-backup" class="small muted"></p><div id="cloud-conflicts"></div></article>
  <article class="card"><h2>Levering til loggtjenester</h2><p>Cloud deler leveringsstatus fra Android-appen med PC-ene.</p><button id="cloud-deliveries" class="secondary" disabled>Hent leveringsstatus</button><div id="cloud-delivery-list" role="status"></div></article>`;
  const main=document.querySelector('main');main.insertBefore(section,main.querySelector('footer'));
  const $=selector=>section.querySelector(selector),form=$('#cloud-connect'),fields=form.elements;
  let pendingVerification=false,busy=false,register=false,registration='open',connected=false,lastSync='',initial=true,editingServer=false,lastState={automatic:false};
  function openAccount(){showPage('cloud');status();}navButton.onclick=openAccount;accountButton.onclick=openAccount;
  function message(text,error=false){$('#cloud-auth-status').textContent=text;$('#cloud-auth-status').classList.toggle('error',error);}
  function controls(){section.querySelectorAll('button,input').forEach(e=>e.disabled=busy);fields.code.disabled=busy||!pendingVerification;fields.code.required=pendingVerification;fields.password_confirm.disabled=busy||!register;fields.password_confirm.required=register;const invite=register&&registration==='invite';fields.invite.disabled=busy||!invite;fields.invite.required=invite;$('#cloud-invite-label').hidden=!invite;for(const id of ['#cloud-auto','#cloud-now','#cloud-deliveries','#cloud-out','#cloud-recovery'])$(id).disabled=busy||!connected;$('#cloud-submit').disabled=busy||(register&&registration==='closed');}
  function mode(value){pendingVerification=false;$('#cloud-verify-group').hidden=true;fields.code.value='';$('#cloud-reset-card').hidden=true;register=value;fields.password.value='';fields.password_confirm.value='';fields.password_confirm.setCustomValidity('');fields.invite.value='';fields.password.type='password';$('#cloud-show-password').textContent='Vis';$('#cloud-show-password').setAttribute('aria-pressed','false');$('#cloud-login-tab').setAttribute('aria-pressed',String(!register));$('#cloud-register-tab').setAttribute('aria-pressed',String(register));$('#cloud-auth-title').textContent=register?'Opprett din HamNavigator-konto':'Velkommen tilbake';$('#cloud-submit').textContent=register?'Opprett konto':'Logg inn';$('#cloud-confirm-label').hidden=!register;$('#cloud-register-info').hidden=!register;$('#cloud-forgot').hidden=register;fields.password.minLength=register?12:1;fields.password.autocomplete=register?'new-password':'current-password';$('#cloud-password-help').textContent=register?'Minst 12 og maksimalt 256 tegn. Bruk et eget passord til HamNavigator.':'Bruk passordet til HamNavigator-kontoen din.';controls();}
  function render(s){
  const previously=window.hnAuthorized===true;window.hnAuthorized=s.authorized===true;
  document.body.classList.toggle('hn-authorized',window.hnAuthorized);
  window.dispatchEvent(new CustomEvent('hamnavigator-cloud-state',{detail:{admin:s.admin===true,authorized:window.hnAuthorized}}));
  if(!window.hnAuthorized && location.hash!=='#language')showPage('cloud');
  else if(window.hnAuthorized&&!previously){refreshState(true).catch(()=>{});if(location.hash!=='#cloud'&&location.hash!=='#language')showPage('home');}
  $('#cloud-retry').hidden=window.hnAuthorized;
  lastState=s;connected=!!s.connected;$('#cloud-auth-card').hidden=connected;$('#cloud-account-card').hidden=!connected;accountButton.textContent=connected?'Min konto':'Logg inn';$('#cloud-account-email').textContent=s.email||'';$('#cloud-account-server').textContent=s.url||'';$('#cloud-status').textContent=s.message+(s.last_sync?' Siste synkronisering: '+s.last_sync:'');$('#cloud-auto').checked=!!s.automatic;$('#cloud-backup').textContent=s.backup_folder?'Lokale sikkerhetskopier: '+s.backup_folder:'';
  if(initial){fields.url.value=s.url||'https://lb7yk.no/cloud';fields.email.value=s.email||'';fields.certificate.value=s.certificate||'';$('#cloud-server-setup').open=!fields.url.value;initial=false;}
  const deliveries=$('#cloud-delivery-list');deliveries.replaceChildren();for(const item of (s.deliveries||[]).slice(-200)){const p=document.createElement('p');p.textContent=[item.call,item.date,item.time,item.service,item.state,item.message].filter(Boolean).join(' · ');deliveries.append(p);}
  const list=$('#cloud-conflicts');list.replaceChildren();const conflicts=s.conflicts||[];let shown=0;
  const names={'panels/layout':'Paneloppsett','setting/call':'Kallesignal','setting/grid':'Stasjonslokator','setting/modules':'Valgte moduler','setting/preferences':'Programinnstillinger','map/preferences':'Kartinnstillinger','digital/preferences':'Digitalinnstillinger'};
  const showMore=()=>{list.querySelector('.cloud-more-conflicts')?.remove();for(const conflict of conflicts.slice(shown,shown+20)){
    const box=document.createElement('details'),title=document.createElement('summary'),q=conflict.local&&typeof conflict.local==='object'?conflict.local:conflict.cloud||{};
    const date=String(q.QSO_DATE||'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$3.$2.$1'),time=String(q.TIME_ON||'').replace(/^(\d{2})(\d{2})(\d{2})$/,'$1:$2:$3');
    title.textContent=conflict.key.startsWith('qso/')?[q.CALL||'Kontakt',date,time?'kl. '+time+' UTC':''].filter(Boolean).join(' · '):(names[conflict.key]||'Lagrede innstillinger');box.append(title);
    if(conflict.fields?.length){const text=document.createElement('p');text.textContent='Ulike opplysninger: '+conflict.fields.join(', ');box.append(text);}
    const pre=document.createElement('pre');pre.style.whiteSpace='pre-wrap';pre.style.overflowWrap='anywhere';pre.textContent=JSON.stringify({denne_PC:conflict.local,skyen:conflict.cloud},null,2);box.append(pre);
    for(const [choice,label] of [['local','Behold denne PC-ens versjon'],['cloud','Bruk skyens versjon']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>send('sync',{choices:{[conflict.key]:choice}});box.append(b);}list.append(box);
  }shown=Math.min(shown+20,conflicts.length);if(shown<conflicts.length){const more=document.createElement('button');more.className='secondary cloud-more-conflicts';more.textContent='Vis flere ('+(conflicts.length-shown)+' igjen)';more.onclick=showMore;list.append(more);}};
  showMore();controls();}
  async function status(){if(busy)return;try{const r=await fetch('/api/cloud/status');if(!r.ok)throw Error();const s=await r.json();if(busy)return;render(s);if(s.last_sync&&s.last_sync!==lastSync){lastSync=s.last_sync;await refreshState();}}catch{if(!busy)$('#cloud-status').textContent='Kan ikke lese skystatus.';}}
  async function send(action,data){if(busy)return;busy=true;controls();message('Arbeider …');try{const r=await fetch('/api/cloud/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Radio-Token':document.querySelector('meta[name="radio-token"]').content},body:JSON.stringify(data)});const s=await r.json();if(!r.ok)throw Error(s.error||'Operasjonen mislyktes.');
  if(s.verification_required){pendingVerification=true;$('#cloud-verify-group').hidden=false;$('#cloud-submit').textContent='Bekreft og logg inn';message(s.message);return true;}
  if(['request-reset','reset-password','resend-verification','verify-email'].includes(action)){message(s.message);}
  else if(action==='recovery'){const blob=new Blob([s.text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HamNavigator-gjenopprettingsnokkel.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Gjenopprettingsnøkkelen er lastet ned. Oppbevar den privat.');}
  else if(action==='check'||action==='import-connection'){registration=s.registration;fields.url.value=s.url;fields.certificate.value=s.certificate;editingServer=false;const text=registration==='open'?'Tilkoblet. Velg Opprett konto eller Logg inn.':registration==='invite'?'Tilkoblet. Serveren krever invitasjonskode.':'Registrering er stengt. Du kan fortsatt logge inn.';$('#cloud-connection-status').textContent=text;message(text);$('#cloud-server-setup').open=false;}
  else{render(s);message(s.message);if(action==='sync')await refreshState(true);}if(action==='connect'&&s.connected){pendingVerification=false;fields.password.value='';fields.password_confirm.value='';fields.invite.value='';fields.recovery.value='';}return true;}catch(e){message(e.message,true);return false;}finally{busy=false;controls();}}
  form.addEventListener('submit',async e=>{e.preventDefault();fields.password_confirm.setCustomValidity(register&&fields.password.value!==fields.password_confirm.value?'Passordene er ikke like.':'');if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));data.register=register;if(register&&editingServer){message('Kontroller servertilkoblingen før du oppretter konto.',true);$('#cloud-server-setup').open=true;return;}if(pendingVerification){if(await send('verify-email',data)){mode(false);fields.password.value=data.password;fields.recovery.value=data.recovery||'';await send('connect',{...data,register:false});}}else await send('connect',data);});
  form.addEventListener('invalid',e=>{if(e.target.name==='url')$('#cloud-server-setup').open=true;},true);fields.password_confirm.oninput=fields.password.oninput=()=>fields.password_confirm.setCustomValidity('');
  for(const key of ['url','certificate'])fields[key].oninput=()=>{editingServer=true;$('#cloud-connection-status').textContent='Kontroller den nye servertilkoblingen før registrering.';registration='open';controls();};
  $('#cloud-login-tab').onclick=()=>mode(false);$('#cloud-register-tab').onclick=()=>mode(true);$('#cloud-show-password').onclick=e=>{const show=fields.password.type==='password';fields.password.type=show?'text':'password';e.target.textContent=show?'Skjul':'Vis';e.target.setAttribute('aria-pressed',String(show));};
  const resetForm=$('#cloud-reset-form'),reset=resetForm.elements;
  $('#cloud-forgot').onclick=()=>{resetForm.reset();reset.reset_email.value=fields.email.value;$('#cloud-reset-card').hidden=false;$('#cloud-reset-card').scrollIntoView({block:'start',behavior:'smooth'});message('Be om en kode til e-postadressen din. Ingen tilgang til serverprogrammet er nødvendig.');};
  $('#cloud-reset-cancel').onclick=()=>{$('#cloud-reset-card').hidden=true;mode(false);};
  $('#cloud-reset-send').onclick=()=>{if(reset.reset_email.reportValidity())send('request-reset',{email:reset.reset_email.value,url:fields.url.value,certificate:fields.certificate.value});};
  reset.reset_confirm.oninput=reset.reset_password.oninput=()=>reset.reset_confirm.setCustomValidity('');
  resetForm.onsubmit=async e=>{e.preventDefault();reset.reset_confirm.setCustomValidity(reset.reset_password.value===reset.reset_confirm.value?'':'Passordene er ikke like.');if(!resetForm.reportValidity())return;const email=reset.reset_email.value,password=reset.reset_password.value;if(await send('reset-password',{email,password,code:reset.reset_code.value,url:fields.url.value,certificate:fields.certificate.value})){mode(false);fields.email.value=email;fields.password.value=password;resetForm.reset();message('Passordet er endret. Trykk Logg inn.');form.scrollIntoView({block:'start'});}};
  $('#cloud-resend').onclick=()=>send('resend-verification',{email:fields.email.value,url:fields.url.value,certificate:fields.certificate.value});
  $('#cloud-standard').onclick=()=>{fields.url.value='https://lb7yk.no/cloud';fields.certificate.value='';editingServer=false;registration='open';$('#cloud-server-setup').open=false;message('HamNavigator Cloud er valgt. Logg inn eller opprett konto.');};
  $('#cloud-retry').onclick=()=>send('verify',{});$('#cloud-now').onclick=()=>send('sync',{});$('#cloud-deliveries').onclick=()=>send('deliveries',{});$('#cloud-recovery').onclick=()=>send('recovery',{});$('#cloud-out').onclick=async()=>{if(await send('disconnect',{}))mode(false);};$('#cloud-auto').onchange=async e=>{if(!await send('auto',{enabled:e.target.checked}))e.target.checked=!!lastState.automatic;};$('#cloud-check').onclick=()=>send('check',{url:fields.url.value,certificate:fields.certificate.value});$('#cloud-import').onclick=()=>$('#cloud-connection-file').click();$('#cloud-connection-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>65536){message('Tilkoblingsfilen er for stor.',true);return;}await send('import-connection',{text:await f.text()});e.target.value='';};
  mode(false);status().then(()=>{if(connected)send('verify',{});});if(location.hash==='#cloud')showPage('cloud',false);setInterval(status,5000);
})();
