using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.Windows.Input;

namespace RadioLog;
public partial class Ft8AdvancedPanel : UserControl
{
 sealed record TxQueueRow(string Call,string Distance,string Frequency,string Message);
 readonly ObservableCollection<Ft8Signal> all;readonly ObservableCollection<Ft8Signal> rx=[];readonly Action start,stop,clear;readonly Action<bool,bool> autoArm;readonly System.Windows.Threading.DispatcherTimer timer;
 bool draggingWaterfall;bool draggingTx;bool lastAdjustedTx;bool syncingMarkers;int lastRxHz=1500,lastTxHz=1500;
 bool useEnglish;
 public static bool EnglishActive { get; private set; }
 static readonly Dictionary<string,string> English=new(StringComparer.Ordinal)
 {
  ["Fil"]="File",["Innstillinger"]="Options",["Palett"]="Palette",["Modus"]="Mode",["Bånd"]="Band",["Språk"]="Language",["Hjelp"]="Help",
  ["Åpne lydfil …"]="Open audio file…",["Vis logg …"]="View log…",["Overskriv locator-database …"]="Overwrite locator database…",["Avslutt"]="Exit",
  ["Lydkort …"]="Sound settings…",["Radio / CAT …"]="Radio / CAT…",["Makroer …"]="Macros…",["Spillkontroll …"]="Playback control…",["Opptakskontroll …"]="Recording control…",["Nettverkskonfigurasjon …"]="Network configuration…",["Radio- og frekvenskonfigurasjon …"]="Radio and frequencies configuration…",["Skriftinnstillinger …"]="Font settings…",["Tekstmarkering …"]="Text highlight…",["Generer meldinger for testtoner …"]="Generate messages for test tones…",["Tidssynkronisering …"]="Time synchronization…",
  ["Valg for dekodelister"]="Decode lists options",["Loggvalg"]="Log options",["Andre valg"]="Other options",["Modusknapper …"]="Mode switcher buttons…",["Båndknapper …"]="Band switcher buttons…",["Vis/skjul waterfall"]="Show/hide waterfall",["Vis/skjul TX-panel"]="Show/hide TX widget",["Vis astronomiske data …"]="View astronomical data…",["MONITOR på ved oppstart"]="Monitor ON at startup",
  ["Standard svart/hvit"]="Default B/W",["Standard farge"]="Default color",["Egendefinert palett"]="Custom palette",["Rediger egendefinert palett …"]="Custom palette editor…",["HamNavigator mørk stil"]="HamNavigator dark style",["FT-tråder"]="FT threads",["Bare 1"]="Only 1",["Maks 2"]="Max 2",["Maks 3"]="Max 3",["Maks 4"]="Max 4",["Maks 5"]="Max 5",["Maks 6"]="Max 6",
  ["Rask • MSK FT Q65"]="Fast • MSK FT Q65",["Normal • MSK FT Q65"]="Normal • MSK FT Q65",["Dyp • MSK FT Q65"]="Deep • MSK FT Q65",["Bruk tretrinns dekoding • FT8"]="Use three-stage decoding • FT8",["Parametere SD Decoder FT8"]="Parameters SD Decoder FT8",
  ["HamNavigator-hjelp"]="HamNavigator help",["Tastatursnarveier"]="Keyboard shortcuts",["Send DX-spot …"]="Send DX spot…",["Om HamNavigator"]="About HamNavigator",
  ["Multi Answering Auto Seq • DXpedition"]="Multi Answering Auto Seq • DXpedition",["Q65"]="Q65",["Vis JT65 DF-akse"]="Show JT65 DF axis",
  ["FT8 MOTOR"]="FT8 ENGINE",["MANUELL LOGG"]="MANUAL LOG",["AKTIVITETSKART"]="ACTIVITY MAP",["LYDKORT"]="SOUND",["RADIO / CAT"]="RADIO / CAT",["LOGGSYNK"]="LOG SYNC",["BRUKSANVISNING"]="USER GUIDE",["AUTO  •  Neste QSO"]="AUTO  •  Next QSO",
  ["LAGRE DISPLAY 1"]="SAVE DISPLAY 1",["LAGRE DISPLAY 2"]="SAVE DISPLAY 2",["DECODE"]="DECODE",["RECEIVE"]="RECEIVE",["MONITOR"]="MONITOR",["STOPP MONITOR"]="STOP MONITOR",["TØM MELDINGER"]="CLEAR MESSAGES",["TØM RX-FREKVENS"]="CLR RX FREQ MSG",["AVSLUTT QSO"]="RESET QSO",["STOPP TX"]="STOP TX",["LEGG TIL LOGGEN"]="ADD TO LOG",["TIL RADIO:"]="TO RADIO:",["LOKATOR:"]="LOCATOR:",["SØK"]="LOOKUP",["LEGG TIL"]="ADD",["Mitt kall"]="My call",["TX FØRSTE"]="TX FIRST",["TX ANDRE"]="TX SECOND",["GEN MLD"]="GEN MSG",["AUTO ER AV"]="AUTO IS OFF",["AUTO NESTE QSO"]="AUTO NEXT QSO",["ARMER TX"]="ARM TX",["SEND VALGT"]="SEND SELECTED",["Kø 0"]="Queue 0",["Nå 0"]="Now 0",["Tid"]="Time",["Melding 0"]="Message 0",["RX Frekvens Melding"]="RX Frequency Message",["Avst"]="Dist",["Køgrense"]="Queue limit",["TX-spor"]="TX slots",["Maks QSO/kall"]="Max QSOs/call",["Autosortering"]="Auto sorting",["Ingen grense"]="No limit",["Sortering av"]="Sort off",["Distanse"]="Distance",["Send CQ på ledig spor"]="Send CQ on free slot",["Spør ved duplikat-QSO"]="Prompt for duplicate QSO",
  ["DESIGNET OG PROGRAMMERT AV STIAN BJERKAN"]="DESIGNED AND PROGRAMMED BY STIAN BJERKAN",["Designet og programmert av Stian Bjerkan • LB7YK"]="Designed and programmed by Stian Bjerkan • LB7YK",["KART"]="MAP",["Gatekart"]="Street map",["Satellitt"]="Satellite",["RADIOFREKVENS"]="RADIO FREQUENCY",["CPU  •  KLAR"]="CPU  •  READY",["Klar"]="Ready",["Motor stoppet"]="Engine stopped",["Ikke oppdatert"]="Not updated",["INGEN LYDINNGANG VALGT"]="NO AUDIO INPUT SELECTED",
  ["Hastighet 9"]="Speed 9",["Hastighet 6"]="Speed 6",["Hastighet 3"]="Speed 3",["TXing: AV"]="TXing: OFF",["LUKK"]="CLOSE",["LAGRE"]="SAVE",["STANDARDVERDIER"]="DEFAULTS",
  ["HamNavigator • Avanserte FT8-innstillinger"]="HamNavigator • Advanced FT8 settings",["AVANSERTE FT8-INNSTILLINGER"]="ADVANCED FT8 SETTINGS",["AUTO SEQ"]="AUTO SEQ",["WATERFALL"]="WATERFALL",["Auto Decode"]="Auto Decode",["Gain"]="Gain",["SD FT8 Decoder (beta)"]="SD FT8 Decoder (beta)",["DX Cluster spots"]="DX Cluster spots",["Fake It / split CAT"]="Fake It / split CAT",["Super Hound"]="Super Hound",["Super Fox"]="Super Fox",
  ["KARTLAG"]="MAP LAYERS",["OPPDATER KARTDATA"]="UPDATE MAP DATA",["Musehjul: zoom • dra • klikk punkt"]="Mouse wheel: zoom • drag • click point",["PUNKTINFORMASJON"]="POINT INFORMATION",["LAGRE INFORMASJON"]="SAVE INFORMATION",["NYTT PUNKT"]="NEW POINT",["Referanse"]="Reference",["Navn/kallesignal"]="Name/call sign",["Breddegrad"]="Latitude",["Lengdegrad"]="Longitude",["Program"]="Program",["Egne notater"]="Notes",["Grønn ring rundt punkt = aktivt nå"]="Green ring around point = active now",["KART  •  klikk et enkeltpunkt for informasjon"]="MAP  •  click a point for information",
  ["⌂  QTH"]="⌂  QTH",["◎  VERDEN"]="◎  WORLD",["▦  RUTENETT"]="▦  GRID",["↗  QSO-LINJER"]="↗  QSO PATHS",["◖  LYDKORT"]="◖  SOUND",["▥  STATISTIKK"]="▥  STATISTICS",["?  HJELP"]="?  HELP",["⌕  FINN KALLESIGNAL"]="⌕  FIND CALL SIGN",["Finn kallesignal i loggen"]="Find call sign in log",["Rød: QTH • Blå: QSO • Gul: Maidenhead"]="Red: QTH • Blue: QSO • Yellow: Maidenhead",["Dra den røde markøren for presis posisjon."]="Drag the red marker for an exact position.",
  ["FT8 LYDKORT"]="FT8 SOUND",["Mottak / inngang"]="Receive / input",["Sending / utgang"]="Transmit / output",["FINN AUTOMATISK"]="DETECT AUTOMATICALLY",["LAGRE VALG"]="SAVE SELECTION",["RADIOOPPSETT"]="RADIO SETUP",["Produsent"]="Manufacturer",["Modell"]="Model",["Baudrate"]="Baud rate",["PTT-metode"]="PTT method",["TEST CAT"]="TEST CAT",["TEST PTT"]="TEST PTT",
  ["AUTOMATISK LOGGOPPLASTING"]="AUTOMATIC LOG UPLOAD",["AKTIVER AUTOMATISK OPPLASTING"]="ENABLE AUTOMATIC UPLOAD",["Brukernavn"]="Username",["Passord"]="Password",["E-post"]="Email",["API-nøkkel"]="API key",["Serveradresse"]="Server address",["Profil-ID"]="Profile ID",["Lokale mål"]="Local targets",["LAGRE SYNKRONISERING"]="SAVE SYNCHRONIZATION",["Ingen opplasting utført ennå."]="No upload performed yet.",
  ["Kallesignal"]="Call sign",["Frekvens MHz"]="Frequency MHz",["RST sendt/mottatt"]="RST sent/received",["Notater for QSO"]="QSO notes",["OTA-program"]="OTA program",["Aktiv referanse"]="Active reference",["Vanlig QSO"]="Normal QSO",["LOGG QSO"]="LOG QSO",["EKSPORTER ADIF"]="EXPORT ADIF",["STASJON"]="STATION",["AKTIVERING"]="ACTIVATION",["SVAR"]="REPLY",["STANS TX"]="STOP TX",["TØM DEKODER"]="CLEAR DECODER",["AKTIVER CQ"]="ENABLE CQ",["▶  START"]="▶  START",["■  STOPP"]="■  STOP",
  ["FT8-DEKODER"]="FT8 DECODER",["Tretrinns dekoding"]="Three-stage decoding",["AP-dekoding"]="AP decoding",["Gjennomsnittsdekoding"]="Average decoding",["Dekodedybde"]="Decoder depth",["Antall dekodertråder"]="Decoder threads",["Bruk filtre ved automatisk sekvens"]="Use filters for automatic sequencing",
  ["WATERFALL OG MARKØRER"]="WATERFALL AND MARKERS",["Kontrast"]="Contrast",["Startfrekvens"]="Start frequency",["Båndbredde"]="Bandwidth",["Vis musemarkører"]="Show mouse markers",["Vis RX-markører"]="Show RX markers",["Vis TX-markører"]="Show TX markers",
  ["AUTOMATISK SEKVENS"]="AUTOMATIC SEQUENCING",["Automatisk neste QSO"]="Automatic next QSO",["Dobbeltklikk på kall slår AUTO på"]="Double-click call sets AUTO on",["Automatisk logging etter RR73/73"]="Automatic logging after RR73/73",["Spør før QSO logges"]="Prompt before logging QSO",["Maksimum samtidige TX-spor"]="Maximum simultaneous TX slots",
  ["MAKROER OG CQ-TYPER"]="MACROS AND CQ TYPES",["CQ-type"]="CQ type",["Egen CQ-tekst"]="Custom CQ text",["Tillat ikke-standard kallesignal"]="Allow non-standard call sign",["Automatisk rapport fra dekodet SNR"]="Automatic report from decoded SNR",["Fritekst"]="Free text",
  ["TID OG SENDING"]="TIME AND TRANSMIT",["Manuell DT-korrigering"]="Manual DT correction",["Blink rødt når DT-korrigering er aktiv"]="Flash red when DT correction is active",["Tune-periode"]="Tune period",["TX første periode (00/30)"]="TX first period (00/30)",["TX andre periode (15/45)"]="TX second period (15/45)",["Hold TX-frekvens"]="Hold TX frequency",
  ["NETTVERK OG RAPPORTERING"]="NETWORK AND REPORTING",["Send radioinformasjon til PSK Reporter"]="Send radio information to PSK Reporter",["UDP-server"]="UDP server",["UDP-port"]="UDP port",["Skriv status til fil"]="Write status to file",["OTP-nøkkel for Super Fox (16 tegn)"]="Super Fox OTP key (16 characters)",
  ["DESIGNET OG PROGRAMMERT AV STIAN BJERKAN • LB7YK"]="DESIGNED AND PROGRAMMED BY STIAN BJERKAN • LB7YK",["HAMNAVIGATOR • BRUKSANVISNING"]="HAMNAVIGATOR • USER GUIDE",
  ["1. KOM I GANG"]="1. GETTING STARTED",["2. STASJONSOPPLYSNINGER"]="2. STATION INFORMATION",["3. FT8 MOTOR"]="3. FT8 ENGINE",["4. MANUELL SSB- OG CW-LOGG"]="4. MANUAL SSB AND CW LOG",["5. AKTIVITETSKART"]="5. ACTIVITY MAP",["7. KARTTYPE OG ZOOM"]="7. MAP TYPE AND ZOOM",["8. LAGRING OG SIKKERHETSKOPI"]="8. STORAGE AND BACKUP",["9. AUTOMATISK LOGGOPPLASTING"]="9. AUTOMATIC LOG UPLOAD",
  ["Start HamNavigator og gå først til LYDKORT. Trykk FINN AUTOMATISK. Kontroller at mottaksinngangen er radioens USB-lydkort eller ønsket lydinngang, og at utgangen er riktig avspillingsenhet. Trykk LAGRE VALG. Gå deretter til RADIO / CAT, velg produsent, radiomodell, COM-port, baudrate og PTT-metode, og trykk LAGRE. Bruk TEST CAT og TEST PTT først når radioen er riktig tilkoblet."]="Start HamNavigator and open SOUND first. Select DETECT AUTOMATICALLY. Verify that the receive input is the radio USB sound device or the required audio input and that the output is the correct playback device. Select SAVE SELECTION. Then open RADIO / CAT, select manufacturer, radio model, COM port, baud rate and PTT method, and select SAVE. Use TEST CAT and TEST PTT only after the radio is connected correctly.",
  ["I FT8 MOTOR skriver du inn ditt eget kallesignal og din Maidenhead-locator. Locator kan ha 4, 6, 8 eller 10 tegn. Flere tegn gir mer nøyaktig plassering. Velg POTA, SOTA eller BOTA og skriv inn aktiv referanse dersom du opererer fra et OTA-punkt."]="In FT8 ENGINE, enter your own call sign and Maidenhead locator. The locator may contain 4, 6, 8 or 10 characters. More characters provide a more accurate position. Select POTA, SOTA or BOTA and enter the active reference when operating from an OTA location.",
  ["Velg korrekt lydkort og CAT-oppsett før motoren startes. START starter mottak og dekoding. Waterfall viser signalaktivitet over lydspekteret, og dekodede meldinger vises i tabellen. AKTIVER CQ starter en CQ-sekvens, SVAR brukes for å besvare valgt stasjon, STANS TX stopper sending, og TØM DEKODER rydder listen. AUTO • Neste QSO gjør motoren klar til å gå videre etter en fullført og logget kontakt. TX må armeres særskilt med TX • Armer sending. Følg alltid lisensvilkår, båndplan, effektgrenser og radioens driftsgrenser. Operatøren er ansvarlig for sendingen."]="Select the correct sound device and CAT configuration before starting the engine. START begins reception and decoding. The waterfall displays signal activity across the audio spectrum, and decoded messages appear in the table. ENABLE CQ starts a CQ sequence, REPLY answers the selected station, STOP TX stops transmission, and CLEAR DECODER clears the list. AUTO • Next QSO prepares the engine to continue after a completed and logged contact. TX must be armed separately with TX • Arm transmit. Always follow licence conditions, band plans, power limits and the radio operating limits. The operator is responsible for all transmissions.",
  ["Åpne MANUELL LOGG. Skriv inn motstasjonens kallesignal, velg SSB eller CW, velg bånd, skriv frekvens i MHz, RST, locator og eventuelt OTA-program og referanse. Notater kan føres i feltet under. Trykk LOGG QSO for å lagre kontakten. Vanlige kontakter uten aktivering logges med Vanlig QSO. EKSPORTER ADIF lager en standard loggfil som kan importeres i andre loggprogrammer og tjenester."]="Open MANUAL LOG. Enter the other station call sign, select SSB or CW, select the band, and enter the frequency in MHz, RST, locator and any OTA program and reference. Notes may be entered in the field below. Select LOG QSO to save the contact. Ordinary contacts without an activation are logged as a normal QSO. EXPORT ADIF creates a standard log file that can be imported into other logging programs and services.",
  ["Velg hvilke lag som skal vises: POTA, WWBOTA og SOTA. OPPDATER KARTDATA henter tilgjengelige aktiveringer. Bruk musehjulet for zoom, hold venstre museknapp og dra for å flytte kartet, og klikk et punkt for å se informasjon. For et eget punkt fyller du ut referanse, navn eller kallesignal, breddegrad, lengdegrad, program og notater og trykker LAGRE INFORMASJON. NYTT PUNKT tømmer feltene. En OTA-referanse som finnes i loggen markeres som aktivert med rød farge."]="Select the layers to display: POTA, WWBOTA and SOTA. UPDATE MAP DATA retrieves available activations. Use the mouse wheel to zoom, hold the left mouse button and drag to move the map, and click a point to view information. To add your own point, enter its reference, name or call sign, latitude, longitude, program and notes, then select SAVE INFORMATION. NEW POINT clears the fields. An OTA reference found in the log is shown as activated in red.",
  ["QTH sentrerer kartet på hjemmeposisjonen. VERDEN viser hele verden. RUTENETT slår Maidenhead-rutenettet av eller på. QSO-LINJER viser forbindelser fra QTH til loggede stasjoner. POTA / SOTA åpner OTA-visningen, mens LOGG går til loggen. Skriv et kallesignal i søkefeltet og trykk FINN KALLESIGNAL for å finne en logget kontakt. Den røde QTH-markøren kan dras med musen for nøyaktig plassering; locator oppdateres etter posisjonen."]="QTH centres the map on the home position. WORLD displays the entire world. GRID toggles the Maidenhead grid. QSO PATHS displays connections from the QTH to logged stations. POTA / SOTA opens the OTA view, while LOG opens the log. Enter a call sign in the search field and select FIND CALL SIGN to locate a logged contact. Drag the red QTH marker for exact placement; the locator is updated from its position.",
  ["Kartvelgeren øverst bytter mellom Gatekart og Satellitt. Karttype gjelder kartvisningene og beholder tilsvarende zoomnivå. Høy detaljgrad krever internettforbindelse fordi kartflisene lastes ved behov."]="The map selector at the top switches between Street map and Satellite. The selected map type applies to the map views and retains the equivalent zoom level. High detail requires an internet connection because map tiles are loaded when required.",
  ["Innstillinger, logg og egne kartpunkter lagres lokalt på PC-en. Eksporter loggen regelmessig som ADIF og oppbevar en sikkerhetskopi på en annen disk eller skylagring. Ikke slå av PC-en mens en lagring eller eksport pågår."]="Settings, the log and custom map points are stored locally on the PC. Export the log regularly as ADIF and keep a backup on another drive or in cloud storage. Do not turn off the PC while saving or exporting.",
  ["Åpne LOGGSYNK. Slå på automatisk opplasting og aktiver bare tjenestene du har konfigurert. For QRZ limer du inn Logbook API-nøkkelen og bruker TEST. For Cloudlog/Wavelog skriver du serveradressen, API-nøkkelen og Station Profile ID. Lokale loggprogrammer kan motta ADIF over UDP på 127.0.0.1; skriv inn porten programmet lytter på. Trykk LAGRE SYNKRONISERING. Etter hver ny kontakt lagrer HamNavigator først lokalt og sender deretter en kopi. Statusfeltet viser resultatet. Ved nettfeil beholdes den lokale loggen."]="Open LOG SYNC. Enable automatic upload and activate only the services you have configured. For QRZ, paste the Logbook API key and use TEST. For Cloudlog/Wavelog, enter the server address, API key and Station Profile ID. Local logging programs can receive ADIF via UDP at 127.0.0.1; enter the port used by the program. Select SAVE SYNCHRONIZATION. After each new contact, HamNavigator saves it locally before sending a copy. The status field displays the result. The local log is retained if a network error occurs.",
  ["HAMNAVIGATOR • EXPLORE • CONNECT • LOG\nDesignet og programmert av Stian Bjerkan • LB7YK"]="HAMNAVIGATOR • EXPLORE • CONNECT • LOG\nDesigned and programmed by Stian Bjerkan • LB7YK",
  ["Full filsti til tqsl.exe"]="Full path to tqsl.exe",["HamNavigator sender én ADIF-post til 127.0.0.1 etter hver QSO. PSK Reporter er en mottaks-/spot-tjeneste og er derfor ikke en QSO-loggbok."]="HamNavigator sends one ADIF record to 127.0.0.1 after each QSO. PSK Reporter is a receive/spot service and is therefore not a QSO logbook.",["Krever QRZ-abonnement med API-tilgang."]="Requires a QRZ subscription with API access.",["Logbook API-nøkkel"]="Logbook API key",["LOKAL ADIF UDP"]="LOCAL ADIF UDP",["Nye FT8-, SSB- og CW-kontakter sendes etter at de er lagret lokalt."]="New FT8, SSB and CW contacts are sent after they have been saved locally.",["Port"]="Port",["Port, for eksempel 2333"]="Port, for example 2333",["Radioene er organisert etter CAT-protokollfamilie. CAT- og PTT-test sender ikke kommandoer før den aktuelle protokolldriveren er ferdig og validert."]="Radios are organised by CAT protocol family. CAT and PTT tests do not send commands until the selected protocol driver has been completed and validated.",["RX-nivå +20 til -20 dB"]="RX level +20 to -20 dB",["TX  •  Armer sending"]="TX  •  Arm transmit",["TX krever valgt lydkort og CAT."]="TX requires a selected sound device and CAT.",["TX-nivå minimum til maksimum"]="TX level minimum to maximum",["Valgfri OTA-referanse"]="Optional OTA reference",["DEKODER"]="DECODER",["MELDINGER"]="MESSAGES",["TID / TX"]="TIME / TX",["NETTVERK"]="NETWORK",
  ["ASeq: svar den fjerneste • MSK FT Q65"]="ASeq: reply to the most distant • MSK FT Q65",["Auto RESET QSO ved slutt • MSK FT Q65"]="Auto RESET QSO at end • MSK FT Q65",["Bruk kø (bare konkurranseaktivitet)"]="Use queue (contest activities only)",["Bruk SD Decoder FT8"]="Use SD Decoder FT8",["Bruk to dekodelister • MSK FT JT65 Q65"]="Use two decode lists • MSK FT JT65 Q65",["Dobbeltklikk på kall slår AUTO på • MSK FT JT65 Q65"]="Double-click call sets AUTO on • MSK FT JT65 Q65",["Enkeltklikk på kall viser land • MSK FT Q65"]="Single-click call shows country • MSK FT Q65",["Filtre for dekodeliste • FT …"]="Decode list filters • FT…",["Gjenkjenn periode • JTMS FSK ISCAT JT6M"]="Recognise period • JTMS FSK ISCAT JT6M",["Gjenkjenn periode • MSK FT JT65 Q65"]="Recognise period • MSK FT JT65 Q65",["Hopp over TX1 • MSK FT Q65"]="Skip TX1 • MSK FT Q65",["Innstillinger for automatisk logginformasjon …"]="Automatic logging information settings…",["Legg kall manuelt i kø med dobbeltklikk"]="Manually add calls to queue by double-click",["Logg QSO automatisk • MSK FT Q65"]="Log QSO automatically • MSK FT Q65",["Ny dekodeperiode tømmer meldingslisten • FT"]="New decode period clears message list • FT",["Slå av automatiske kommentarer"]="Turn automatic comments off",["Slå av JT65-markører"]="Turn off JT65 markers",["Slå på musemarkører • FT Q65"]="Turn on mouse markers • FT Q65",["Slå på RX-markører • FT Q65"]="Turn on RX markers • FT Q65",["Slå på TX-markører • FT Q65"]="Turn on TX markers • FT Q65",["Spør før QSO logges • MSK FT Q65"]="Prompt before logging QSO • MSK FT Q65",["Startdato/-tid = sluttdato/-tid"]="Start date/time = end date/time",["TX-bekreftelse ved 73/RR73 • FT Q65"]="TX confirmation at 73/RR73 • FT Q65",["Varsle hvis QSO finnes fra før"]="Warn if QSO exists already",["Vis/skjul avstandskolonne • MSK FT"]="Show/hide distance column • MSK FT",["Vis/skjul frekvenskolonne • MSK FT"]="Show/hide frequency column • MSK FT",["Vis/skjul landkolonne • MSK FT Q65"]="Show/hide country column • MSK FT Q65",["Vis/skjul tidskolonne • FT"]="Show/hide time column • FT",
  ["Aggressive nivåer • JT65 …"]="Aggressive levels • JT65…",["Aktiver AP • FT JT65 Q65"]="Enable AP • FT JT65 Q65",["Aktiver Deep Search • JT65"]="Enable Deep Search • JT65",["Aktiver gjennomsnitt • JT65 Q65 FT2"]="Enable averaging • JT65 Q65 FT2",["Dekode etter EME-forsinkelse • Q65"]="Decode after EME delay • Q65",["Enkelt dekodet signal • JT65"]="Single decoded signal • JT65",["Enkelt dekodet signal • Q65"]="Single decoded signal • Q65",["Følsomhet – lave terskler"]="Sensitivity – low thresholds",["Følsomhet – subpass"]="Sensitivity – subpass",["Følsomhet minimum"]="Sensitivity minimum",["MSK RX-utjevning av"]="MSK RX equalisation off",["MSK RX-utjevning dynamisk"]="MSK RX equalisation dynamic",["MSK RX-utjevning S og D"]="MSK RX equalisation S and D",["MSK RX-utjevning statisk"]="MSK RX equalisation static",["Multi Answering Auto Seq • Standard"]="Multi Answering Auto Seq • Standard",["Tøm gjennomsnitt automatisk etter dekoding • Q65"]="Auto-clear averaging after decode • Q65"
 };
 public event Action<string>? NavigateRequested;
 readonly TextBox frequencyInput=new(){Width=112,Height=26,Text="14.074.000",FontWeight=FontWeights.Bold,HorizontalContentAlignment=HorizontalAlignment.Center};readonly CheckBox autoCat=new(){Content="AUTO CAT",IsChecked=true};public bool AutoCatEnabled=>autoCat.IsChecked==true;public double ManualFrequencyMhz=>double.TryParse(frequencyInput.Text.Replace(".","").Replace(",",""),out var raw)?raw/1_000_000d:14.074;public void SetFrequency(double mhz){frequencyInput.Text=(mhz*1_000_000).ToString("000000000").Insert(3,".").Insert(7,".");}
 public Ft8AdvancedPanel(ObservableCollection<Ft8Signal> decoded,string call,string grid,Action startEngine,Action stopEngine,Action clearMessages,Action<bool,bool> setAutoArm)
 {InitializeComponent();BuildMenuHeader();AddFrequencyControl();StyleMenuItems(this);WireFrontPanelControls();AddNumericSpinners();var bottomButtons=FindChild<UniformGrid>(this);if(bottomButtons!=null)bottomButtons.Columns=4;LabelSliders();all=decoded;start=startEngine;stop=stopEngine;clear=clearMessages;autoArm=setAutoArm;AllMessages.ItemsSource=all;RxMessages.ItemsSource=rx;StationCall.Text=call;StationGrid.Text=grid;timer=new(){Interval=TimeSpan.FromSeconds(1)};timer.Tick+=(_,_)=>{var culture=useEnglish?System.Globalization.CultureInfo.GetCultureInfo("en-US"):System.Globalization.CultureInfo.GetCultureInfo("nb-NO");UtcClock.Text=DateTime.UtcNow.ToString("dd MMM yyyy  HH:mm:ss 'UTC'",culture);CpuText.Text=useEnglish?$"CPU  •  DECODED {all.Count}":$"CPU  •  DEKODET {all.Count}";if(all.Count>0&&rx.Count==0)rx.Add(all[0]);DrawWaterfall();};timer.Start();Loaded+=(_,_)=>{DrawScale();DrawWaterfall();DrawFrequencyMarkers();};}
 void WireFrontPanelControls()
 {
  var txToRx=FindChildren<Button>(this).FirstOrDefault(b=>(b.Content?.ToString()??"")=="TX = RX");if(txToRx?.Parent is not WrapPanel row)return;txToRx.ToolTip="Kopier TX-lydfrekvens til RX";txToRx.Click+=(_,_)=>SetBothMarkers(ReadAudioFrequency(TxHz,1500));
  var rxToTx=new Button{Content="RX = TX",ToolTip="Kopier RX-lydfrekvens til TX"};rxToTx.Click+=(_,_)=>SetBothMarkers(ReadAudioFrequency(RxHz,1500));row.Children.Insert(row.Children.IndexOf(txToRx)+1,rxToTx);
 }
 void AddNumericSpinners()
 {
  foreach(var box in FindChildren<TextBox>(this).ToArray())
  {
   if(box==frequencyInput||!int.TryParse(box.Text,out _ )||box.Parent is not Panel parent)continue;
   int index=parent.Children.IndexOf(box);if(index<0)continue;int step=(box==RxHz||box==TxHz)?5:1;
   var arrows=new Grid{Width=18,Height=27,Margin=new Thickness(-2,2,2,2),ToolTip=$"Juster med ±{step}"};arrows.RowDefinitions.Add(new RowDefinition());arrows.RowDefinitions.Add(new RowDefinition());
   RepeatButton Arrow(string text,int delta,int row){var b=new RepeatButton{Content=text,FontSize=7,FontWeight=FontWeights.Bold,Padding=new Thickness(0),Margin=new Thickness(0),MinHeight=0,Background=new SolidColorBrush(Color.FromRgb(16,55,82)),Foreground=Brushes.White,BorderBrush=new SolidColorBrush(Color.FromRgb(63,174,220)),BorderThickness=new Thickness(1),Delay=350,Interval=75};b.Click+=(_,_)=>AdjustNumeric(box,delta);Grid.SetRow(b,row);return b;}
   arrows.Children.Add(Arrow("▲",step,0));arrows.Children.Add(Arrow("▼",-step,1));parent.Children.Insert(index+1,arrows);
  }
 }
 static void AdjustNumeric(TextBox box,int delta)
 {
  if(!int.TryParse(box.Text,out int value))value=0;int min=(box.Name=="RxHz"||box.Name=="TxHz")?0:-50,max=(box.Name=="RxHz"||box.Name=="TxHz")?3200:9999;box.Text=Math.Clamp(value+delta,min,max).ToString();box.CaretIndex=box.Text.Length;
 }
 void AddFrequencyControl(){if(CpuText.Parent is not DockPanel dock)return;var box=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(10,0,10,0)};box.Children.Add(new TextBlock{Text="RADIOFREKVENS",Foreground=new SolidColorBrush(Color.FromRgb(98,223,255)),VerticalAlignment=VerticalAlignment.Center,FontWeight=FontWeights.Bold,Margin=new Thickness(0,0,5,0)});box.Children.Add(frequencyInput);box.Children.Add(autoCat);DockPanel.SetDock(box,Dock.Right);int cpu=dock.Children.IndexOf(CpuText);dock.Children.Insert(Math.Max(0,cpu),box);}
 void BuildMenuHeader()
 {
  if(CpuText.Parent is not Border host)return;host.Child=null;
  var dock=new DockPanel();var menu=new Menu{Background=new SolidColorBrush(Color.FromRgb(9,24,39)),Foreground=Brushes.White,VerticalAlignment=VerticalAlignment.Center};
  MenuItem Root(string title){var m=new MenuItem{Header=title};menu.Items.Add(m);return m;}
  MenuItem Item(ItemsControl parent,string text,string group,bool check=false){var m=new MenuItem{Header=text,Tag=group,Uid=text,IsCheckable=check};m.Click+=MenuClick;parent.Items.Add(m);return m;}
  MenuItem Sub(ItemsControl parent,string text){var m=new MenuItem{Header=text};parent.Items.Add(m);return m;}
  void Sep(ItemsControl parent)=>parent.Items.Add(new Separator());

  var file=Root("Fil");Item(file,"Åpne lydfil …","Fil");Item(file,"Vis logg …","Fil");Item(file,"Overskriv locator-database …","Fil");Sep(file);Item(file,"Avslutt","Fil");

  var options=Root("Innstillinger");
  Item(options,"Lydkort …","Innstillinger");Item(options,"Radio / CAT …","Innstillinger");Item(options,"Makroer …","Innstillinger");Item(options,"Spillkontroll …","Innstillinger");Item(options,"Opptakskontroll …","Innstillinger");Item(options,"Nettverkskonfigurasjon …","Innstillinger");Item(options,"Radio- og frekvenskonfigurasjon …","Innstillinger");Item(options,"Skriftinnstillinger …","Innstillinger");Item(options,"Tekstmarkering …","Innstillinger");Item(options,"Generer meldinger for testtoner …","Innstillinger");Item(options,"Tidssynkronisering …","Innstillinger");
  var lists=Sub(options,"Valg for dekodelister");Item(lists,"Bruk to dekodelister • MSK FT JT65 Q65","Dekodelister",true);Item(lists,"Dobbeltklikk på kall slår AUTO på • MSK FT JT65 Q65","Dekodelister",true);Item(lists,"Ny dekodeperiode tømmer meldingslisten • FT","Dekodelister",true);Item(lists,"Enkeltklikk på kall viser land • MSK FT Q65","Dekodelister",true);Item(lists,"Vis/skjul tidskolonne • FT","Dekodelister",true);Item(lists,"Vis/skjul landkolonne • MSK FT Q65","Dekodelister",true);Item(lists,"Vis/skjul avstandskolonne • MSK FT","Dekodelister",true);Item(lists,"Vis/skjul frekvenskolonne • MSK FT","Dekodelister",true);Item(lists,"Filtre for dekodeliste • FT …","Dekodelister");
  var log=Sub(options,"Loggvalg");Item(log,"Logg QSO automatisk • MSK FT Q65","Loggvalg",true);Item(log,"Spør før QSO logges • MSK FT Q65","Loggvalg",true);Item(log,"Varsle hvis QSO finnes fra før","Loggvalg",true);Item(log,"Startdato/-tid = sluttdato/-tid","Loggvalg",true);Item(log,"Slå av automatiske kommentarer","Loggvalg",true);Item(log,"Innstillinger for automatisk logginformasjon …","Loggvalg");
  var other=Sub(options,"Andre valg");Item(other,"Hopp over TX1 • MSK FT Q65","Andre valg",true);Item(other,"Bruk kø (bare konkurranseaktivitet)","Andre valg",true);Sep(other);Item(other,"Gjenkjenn periode • JTMS FSK ISCAT JT6M","Andre valg",true);Item(other,"Gjenkjenn periode • MSK FT JT65 Q65","Andre valg",true);Sep(other);Item(other,"Vis JT65 DF-akse","Andre valg",true);Item(other,"Slå av JT65-markører","Andre valg",true);Item(other,"Slå på musemarkører • FT Q65","Andre valg",true);Item(other,"Slå på RX-markører • FT Q65","Andre valg",true);Item(other,"Slå på TX-markører • FT Q65","Andre valg",true);Sep(other);Item(other,"Multi Answering Auto Seq • DXpedition","Andre valg",true);Item(other,"Multi Answering Auto Seq • Standard","Andre valg",true);Item(other,"Legg kall manuelt i kø med dobbeltklikk","Andre valg",true);
  Sep(options);Item(options,"Modusknapper …","Innstillinger");Item(options,"Båndknapper …","Innstillinger");Item(options,"Vis/skjul waterfall","Innstillinger",true);Item(options,"Vis/skjul TX-panel","Innstillinger",true);Item(options,"Vis astronomiske data …","Innstillinger");Sep(options);Item(options,"ASeq: svar den fjerneste • MSK FT Q65","Innstillinger",true);Item(options,"TX-bekreftelse ved 73/RR73 • FT Q65","Innstillinger",true);Item(options,"Auto RESET QSO ved slutt • MSK FT Q65","Innstillinger",true);Sep(options);Item(options,"MONITOR på ved oppstart","Innstillinger",true);

  var palette=Root("Palett");foreach(var p in new[]{"Standard svart/hvit","Standard farge","Palett 1","Palett 2","Palett 3","Palett 4","Palett 5","Palett 6","Egendefinert palett"})Item(palette,p,"Palett",true);Sep(palette);Item(palette,"Rediger egendefinert palett …","Palett");Sep(palette);Item(palette,"HamNavigator mørk stil","Palett",true).IsChecked=true;
  var mode=Root("Modus");foreach(var m in new[]{"MSK144","MSKMS","JTMS","FSK441","FSK315","ISCAT-A","ISCAT-B","JT6M","FT2","FT4","FT8","PI4","JT65A • HF/50 MHz","JT65B • VHF/UHF","JT65C • VHF/UHF"})Item(mode,m,"Modus",true);var q65=Sub(mode,"Q65");foreach(var m in new[]{"Q65A","Q65B","Q65C","Q65D"})Item(q65,m,"Modus",true);
  var decode=Root("Decode");var threads=Sub(decode,"FT-tråder");foreach(var t in new[]{"Bare 1","Maks 2","Maks 3","Maks 4","Maks 5","Maks 6"})Item(threads,t,"Decode",true);Sep(decode);foreach(var d in new[]{"Rask • MSK FT Q65","Normal • MSK FT Q65","Dyp • MSK FT Q65","Bruk tretrinns dekoding • FT8"})Item(decode,d,"Decode",true);Sep(decode);Item(decode,"Bruk SD Decoder FT8","Decode",true);var sd=Sub(decode,"Parametere SD Decoder FT8");foreach(var d in new[]{"Dekodersykluser 1","Dekodersykluser 2","Dekodersykluser 3","Følsomhet minimum","Følsomhet – lave terskler","Følsomhet – subpass"})Item(sd,d,"Decode",true);Sep(decode);foreach(var d in new[]{"MSK RX-utjevning av","MSK RX-utjevning statisk","MSK RX-utjevning dynamisk","MSK RX-utjevning S og D","Enkelt dekodet signal • Q65","Driftkorreksjon ±100 Hz • Q65","Enkelt dekodet signal • JT65","Maks 4 dekodede signaler • JT65","Maks 8 dekodede signaler • JT65","Maks 16 dekodede signaler • JT65","Maks 32 dekodede signaler • JT65","Aggressive nivåer • JT65 …","VHF/UHF-funksjoner • JT65","Aktiver gjennomsnitt • JT65 Q65 FT2","Tøm gjennomsnitt automatisk etter dekoding • Q65","Aktiver Deep Search • JT65","Dekode etter EME-forsinkelse • Q65","Aktiver AP • FT JT65 Q65"})Item(decode,d,"Decode",true);
  var band=Root("Bånd");void Bands(string title,string[] values){var b=Sub(band,title);foreach(var v in values)Item(b,v,"Bånd",true);}Bands("VLF",new[]{"135 kHz","472 kHz","501 kHz"});Bands("HF/VHF",new[]{"1.8 MHz","3.5 MHz","5 MHz","7 MHz","10 MHz","14 MHz","18 MHz","21 MHz","24 MHz","27 MHz","28 MHz","40 MHz","50 MHz","60 MHz"});Bands("VHF/UHF",new[]{"70 MHz","144 MHz","222 MHz","432 MHz","902 MHz","1296 MHz","2320 MHz"});Bands("SHF/EHF",new[]{"3.4 GHz","5.65 GHz","10 GHz","24 GHz","47 GHz","76 GHz","120 GHz","144 GHz","248 GHz"});
  var language=Root("Språk");foreach(var l in new[]{"English","Български","Русский","Norsk","Deutsch","Français","Italiano","Español","Català","Português","Português do Brasil","Română","Dansk","Polski","Čeština","中文"})Item(language,l,"Språk",true);
  var help=Root("Hjelp");Item(help,"HamNavigator-hjelp","Hjelp");Item(help,"Tastatursnarveier","Hjelp");Item(help,"Send DX-spot …","Hjelp");Sep(help);Item(help,"Om HamNavigator","Hjelp");
  DockPanel.SetDock(menu,Dock.Left);dock.Children.Add(menu);DockPanel.SetDock(CpuText,Dock.Right);dock.Children.Add(CpuText);host.Child=dock;
 }
 void MenuClick(object sender,RoutedEventArgs e)
 {
  if(sender is not MenuItem m)return;string text=string.IsNullOrWhiteSpace(m.Uid)?m.Header?.ToString()??"":m.Uid,group=m.Tag?.ToString()??"";
  if(text=="Avslutt"){Window.GetWindow(this)?.Close();return;}
  if(text=="Vis logg …"){if(Window.GetWindow(this) is MainWindow main)main.MainTabs.SelectedIndex=1;return;}
  if(text.Contains("Lydkort")||text.Contains("Spillkontroll")||text.Contains("Opptakskontroll")){NavigateRequested?.Invoke("LYDKORT");return;}
  if(text.Contains("Radio / CAT")||text.Contains("Radio- og frekvens")){NavigateRequested?.Invoke("RADIO");return;}
  if(text.Contains("Nettverkskonfigurasjon")||text.Contains("automatisk logginformasjon")){NavigateRequested?.Invoke("LOGGSYNK");return;}
  if(text=="HamNavigator-hjelp"||text=="Tastatursnarveier"){NavigateRequested?.Invoke("BRUKSANVISNING");return;}
  if(text=="Om HamNavigator"){MessageBox.Show(useEnglish?"HamNavigator\nDesigned and programmed by Stian Bjerkan • LB7YK\n\nMSHV menus mapped against the official MSHV 2.76.6 source code.":"HamNavigator\nDesignet og programmert av Stian Bjerkan • LB7YK\n\nMSHV-menyer kartlagt mot offisiell MSHV 2.76.6-kildekode.",useEnglish?"About HamNavigator":"Om HamNavigator");return;}
  if(group=="Modus"){SelectOnly(m);Txing.Text=(useEnglish?"Mode: ":"Modus: ")+text.Split('•')[0].Trim();return;}
  if(group=="Bånd"){SelectOnly(m);Txing.Text=(useEnglish?"Band: ":"Bånd: ")+text;SetBandFrequency(text);return;}
  if(group=="Språk"){SelectOnly(m);ApplyLanguage(text);return;}
  if(group=="Palett"){if(text.Contains("Rediger")){ShowSettings("WATERFALL");return;}SelectOnly(m);DrawWaterfall();return;}
  if(group=="Decode"){Txing.Text=(useEnglish?"Decoder: ":"Dekoder: ")+Translate(text,useEnglish);return;}
  if(text=="Vis/skjul waterfall"){Waterfall.Visibility=m.IsChecked?Visibility.Visible:Visibility.Collapsed;return;}
  string page=text switch{"Makroer …"=>"MELDINGER","Tekstmarkering …"=>"WATERFALL","Generer meldinger for testtoner …"=>"TID / TX","Tidssynkronisering …"=>"TID / TX","Vis astronomiske data …"=>"TID / TX","Filtre for dekodeliste • FT …"=>"DEKODER","Multi Answering Auto Seq • DXpedition"=>"AUTO SEQ","Multi Answering Auto Seq • Standard"=>"AUTO SEQ",_=>""};
  if(page.Length>0){ShowSettings(page);return;}
  if(m.IsCheckable){Txing.Text=$"{Translate(text,useEnglish)}: {(useEnglish?(m.IsChecked?"ON":"OFF"):(m.IsChecked?"PÅ":"AV"))}";return;}
  MessageBox.Show(useEnglish?$"“{Translate(text,true)}” is in the correct MSHV menu position, but its HamNavigator dialog has not yet been implemented.":$"«{text}» er lagt på korrekt plass som i MSHV, men den tilhørende HamNavigator-dialogen er ennå ikke implementert.","HamNavigator");
 }
 void ShowSettings(string page){var window=new AdvancedFt8SettingsWindow(page){Owner=Window.GetWindow(this)};if(useEnglish)ApplyTranslations(window,true);window.ShowDialog();}
 void ApplyLanguage(string language)
 {
  if(language is not ("Norsk" or "English")){MessageBox.Show($"Språkpakken for {language} er synlig fordi menyen følger MSHV, men den er ikke oversatt i HamNavigator ennå. Norsk og English er aktive språkpakker.","HamNavigator • språk");return;}
  useEnglish=language=="English";EnglishActive=useEnglish;DependencyObject root=Window.GetWindow(this) is Window window?window:this;ApplyTranslations(root,useEnglish);if(Window.GetWindow(this) is MainWindow languageWindow)languageWindow.RefreshDynamicLanguage();if(useEnglish&&Window.GetWindow(this) is MainWindow main&&main.Footer.Text.StartsWith("GridTracker sentrert på"))main.Footer.Text=main.Footer.Text.Replace("GridTracker sentrert på","GridTracker centered on");else if(!useEnglish&&Window.GetWindow(this) is MainWindow norsk&&norsk.Footer.Text.StartsWith("GridTracker centered on"))norsk.Footer.Text=norsk.Footer.Text.Replace("GridTracker centered on","GridTracker sentrert på");Txing.Text=useEnglish?"Language: English":"Språk: Norsk";
 }
 static string Translate(string value,bool english)
 {
  if(english)return English.TryGetValue(value,out var translated)?translated:value;foreach(var pair in English)if(pair.Value==value)return pair.Key;return value;
 }
 public static string UiText(string norwegian)=>Translate(norwegian,EnglishActive);
 static void ApplyTranslations(DependencyObject root,bool english)
 {
  switch(root)
  {
   case Window window when !string.IsNullOrWhiteSpace(window.Title):window.Title=Translate(window.Title,english);break;
   case DataGrid grid:foreach(var column in grid.Columns)if(column.Header is string value)column.Header=Translate(value,english);break;
   case TextBlock text when !string.IsNullOrWhiteSpace(text.Text):text.Text=Translate(text.Text,english);break;
   case HeaderedItemsControl header when header.Header is string value:header.Header=Translate(value,english);break;
   case HeaderedContentControl header when header.Header is string value:header.Header=Translate(value,english);break;
   case ContentControl content when content.Content is string value:content.Content=Translate(value,english);break;
  }
  if(root is FrameworkElement element&&element.ToolTip is string tip)element.ToolTip=Translate(tip,english);
  foreach(var child in LogicalTreeHelper.GetChildren(root))if(child is DependencyObject dependency)ApplyTranslations(dependency,english);
 }
 static void SelectOnly(MenuItem selected){if(selected.Parent is ItemsControl parent)foreach(var item in parent.Items.OfType<MenuItem>())if(item.IsCheckable)item.IsChecked=ReferenceEquals(item,selected);}
 void SetBandFrequency(string band){var mhz=band switch{"1.8 MHz"=>1.840,"3.5 MHz"=>3.573,"5 MHz"=>5.357,"7 MHz"=>7.074,"10 MHz"=>10.136,"14 MHz"=>14.074,"18 MHz"=>18.100,"21 MHz"=>21.074,"24 MHz"=>24.915,"27 MHz"=>27.245,"28 MHz"=>28.074,"50 MHz"=>50.313,"70 MHz"=>70.154,"144 MHz"=>144.174,_=>0};if(mhz>0)SetFrequency(mhz);}
 static void StyleMenuItems(DependencyObject root){foreach(var item in LogicalTreeHelper.GetChildren(root)){if(item is MenuItem m){m.Foreground=Brushes.White;m.Background=new SolidColorBrush(Color.FromRgb(10,31,50));m.Padding=new Thickness(8,4,14,4);foreach(var sub in m.Items.OfType<MenuItem>()){sub.Foreground=Brushes.White;sub.Background=new SolidColorBrush(Color.FromRgb(10,31,50));sub.Padding=new Thickness(12,6,24,6);}}if(item is DependencyObject child)StyleMenuItems(child);}}
 static T? FindChild<T>(DependencyObject root) where T:DependencyObject{foreach(var item in LogicalTreeHelper.GetChildren(root)){if(item is T hit)return hit;if(item is DependencyObject child&&FindChild<T>(child) is T nested)return nested;}return null;}
 static IEnumerable<T> FindChildren<T>(DependencyObject root) where T:DependencyObject{foreach(var item in LogicalTreeHelper.GetChildren(root))if(item is DependencyObject child){if(child is T hit)yield return hit;foreach(var nested in FindChildren<T>(child))yield return nested;}}
 void LabelSliders(){string[] names={"WF GAIN","DT","DF TOL","RX","TX"};var sliders=FindChildren<Slider>(this).ToArray();for(int i=0;i<sliders.Length&&i<names.Length;i++){var slider=sliders[i];slider.ToolTip=names[i];if((slider==RxLevel||slider==TxLevel))continue;if(slider.Orientation==Orientation.Vertical&&slider.Parent is Grid g){var label=new TextBlock{Text=names[i],Foreground=new SolidColorBrush(Color.FromRgb(98,223,255)),Background=new SolidColorBrush(Color.FromArgb(210,7,17,31)),FontSize=9,FontWeight=FontWeights.Bold,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Top,Padding=new Thickness(2,1,2,1)};Grid.SetColumn(label,Grid.GetColumn(slider));Grid.SetRow(label,Grid.GetRow(slider));Panel.SetZIndex(label,3);g.Children.Add(label);}}}
 void ScaleChanged(object s,SizeChangedEventArgs e)=>DrawScale();void DrawScale(){if(ScaleCanvas==null)return;ScaleCanvas.Children.Clear();double w=ScaleCanvas.ActualWidth;for(int hz=0;hz<=3200;hz+=100){double x=hz/3200d*w;ScaleCanvas.Children.Add(new Line{X1=x,X2=x,Y1=hz%500==0?8:17,Y2=28,Stroke=Brushes.Black,StrokeThickness=1});if(hz%500==0){var t=new TextBlock{Text=hz.ToString(),Foreground=Brushes.Black,FontSize=10};Canvas.SetLeft(t,x+2);ScaleCanvas.Children.Add(t);}}}
 void DrawWaterfall(){if(Waterfall==null||ActualWidth<20)return;int w=Math.Max(400,(int)ActualWidth),h=180;var p=new byte[w*h*4];var now=DateTime.UtcNow.Millisecond;double tune=WaterfallTune?.Value??50,contrast=(WaterfallContrast?.Value??12)/12d;for(int y=0;y<h;y++)for(int x=0;x<w;x++){int i=(y*w+x)*4;double sig=Math.Exp(-Math.Pow((x-w*.46)/18,2))+0.7*Math.Exp(-Math.Pow((x-w*.68)/10,2));double baseline=(tune-50)*1.8,noise=((x*13+y*7+now/10)%18)*contrast;p[i]=(byte)Math.Clamp(15+baseline+noise+sig*230*contrast,0,255);p[i+1]=(byte)Math.Clamp(8+baseline+noise+sig*150*contrast,0,255);p[i+2]=(byte)Math.Clamp(20+baseline+noise+sig*30*contrast,0,255);p[i+3]=255;}var b=new WriteableBitmap(w,h,96,96,PixelFormats.Bgra32,null);b.WritePixels(new Int32Rect(0,0,w,h),p,w*4,0);Waterfall.Source=b;if(Waterfall2!=null)Waterfall2.Source=b.Clone();DrawFrequencyMarkers();}
 void WaterfallVisualChanged(object s,RoutedPropertyChangedEventArgs<double> e){if(IsLoaded)DrawWaterfall();}
 void ToggleDisplayMode(object s,RoutedEventArgs e){bool two=Waterfall2.Visibility!=Visibility.Visible;Waterfall2.Visibility=two?Visibility.Visible:Visibility.Collapsed;SecondDisplayRow.Height=two?new GridLength(1,GridUnitType.Star):new GridLength(0);DisplayModeButton.Content=two?"2D":"1D";DrawWaterfall();e.Handled=true;}
 int ReadAudioFrequency(TextBox box,int fallback)=>int.TryParse(box.Text,out var hz)?Math.Clamp(hz,0,3200):fallback;
 void SetBothMarkers(int hz){hz=Math.Clamp(hz,0,3200);syncingMarkers=true;RxHz.Text=hz.ToString();TxHz.Text=hz.ToString();lastRxHz=lastTxHz=hz;syncingMarkers=false;DrawFrequencyMarkers();}
 bool MarkersLocked()=>FindChildren<CheckBox>(this).FirstOrDefault(x=>(x.Content?.ToString()??"")=="LTR")?.IsChecked==true;
 void DrawFrequencyMarkers()
 {
  if(Overlay==null||Overlay.ActualWidth<=1)return;Overlay.Children.Clear();int rxHz=ReadAudioFrequency(RxHz,1500),txHz=ReadAudioFrequency(TxHz,1500);double h=Math.Max(1,Overlay.ActualHeight),rxX=rxHz/3200d*Overlay.ActualWidth,txX=txHz/3200d*Overlay.ActualWidth;
  void Marker(double x,Brush color,double dash){Overlay.Children.Add(new Line{X1=x-dash,X2=x-dash,Y1=0,Y2=h,Stroke=Brushes.Black,StrokeThickness=4});Overlay.Children.Add(new Line{X1=x-dash,X2=x-dash,Y1=0,Y2=h,Stroke=color,StrokeThickness=2});var tri=new Polygon{Fill=color,Points=new PointCollection{new(x-dash-6,0),new(x-dash+6,0),new(x-dash,9)}};Overlay.Children.Add(tri);}
  Marker(rxX,Brushes.LimeGreen,rxHz==txHz?-2:0);Marker(txX,Brushes.OrangeRed,rxHz==txHz?2:0);RxMarker.Text=$"RX: {rxHz} Hz   TX: {txHz} Hz";
 }
 void SetWaterfallFrequency(Point point,bool tx)
 {
  if(Overlay.ActualWidth<=1)return;int hz=(int)Math.Round(Math.Clamp(point.X,0,Overlay.ActualWidth)/Overlay.ActualWidth*3200/5d)*5;hz=Math.Clamp(hz,0,3200);if(tx)TxHz.Text=hz.ToString();else RxHz.Text=hz.ToString();lastAdjustedTx=tx;DrawFrequencyMarkers();
 }
 void WaterfallMouseDown(object sender,MouseButtonEventArgs e)
 {
  draggingWaterfall=true;draggingTx=e.ChangedButton==MouseButton.Right||(Keyboard.Modifiers&ModifierKeys.Shift)!=0;WaterfallHost.CaptureMouse();SetWaterfallFrequency(e.GetPosition(Overlay),draggingTx);if(e.ClickCount>=2){int hz=ReadAudioFrequency(draggingTx?TxHz:RxHz,1500);syncingMarkers=true;RxHz.Text=hz.ToString();TxHz.Text=hz.ToString();lastRxHz=lastTxHz=hz;syncingMarkers=false;DrawFrequencyMarkers();}e.Handled=true;
 }
 void WaterfallMouseMove(object sender,MouseEventArgs e){if(draggingWaterfall)SetWaterfallFrequency(e.GetPosition(Overlay),draggingTx);}
 void WaterfallMouseUp(object sender,MouseButtonEventArgs e){draggingWaterfall=false;WaterfallHost.ReleaseMouseCapture();e.Handled=true;}
 void WaterfallMouseWheel(object sender,MouseWheelEventArgs e){var box=lastAdjustedTx?TxHz:RxHz;int hz=ReadAudioFrequency(box,1500)+(e.Delta>0?5:-5);box.Text=Math.Clamp(hz,0,3200).ToString();e.Handled=true;}
 void FrequencyTextChanged(object sender,TextChangedEventArgs e)
 {
  if(RxHz==null||TxHz==null)return;int rx=ReadAudioFrequency(RxHz,lastRxHz),tx=ReadAudioFrequency(TxHz,lastTxHz);if(!syncingMarkers&&MarkersLocked()){syncingMarkers=true;if(ReferenceEquals(sender,RxHz)){int delta=rx-lastRxHz;tx=Math.Clamp(lastTxHz+delta,0,3200);TxHz.Text=tx.ToString();}else if(ReferenceEquals(sender,TxHz)){int delta=tx-lastTxHz;rx=Math.Clamp(lastRxHz+delta,0,3200);RxHz.Text=rx.ToString();}syncingMarkers=false;}lastRxHz=ReadAudioFrequency(RxHz,rx);lastTxHz=ReadAudioFrequency(TxHz,tx);DrawFrequencyMarkers();
 }
 void SaveDisplayClick(object sender,RoutedEventArgs e)
 {
  string which=(sender as Button)?.Content?.ToString()?.EndsWith("2")==true?"2":"1";var selectedDisplay=which=="2"&&Waterfall2.Visibility==Visibility.Visible?Waterfall2:Waterfall;if(selectedDisplay.Source is not BitmapSource bitmap)return;var dialog=new Microsoft.Win32.SaveFileDialog{Title=useEnglish?$"Save display {which}":$"Lagre display {which}",Filter=useEnglish?"PNG image (*.png)|*.png":"PNG-bilde (*.png)|*.png",FileName=$"HamNavigator-display-{which}-{DateTime.Now:yyyyMMdd-HHmmss}.png"};if(dialog.ShowDialog(Window.GetWindow(this))!=true)return;var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using var stream=System.IO.File.Create(dialog.FileName);encoder.Save(stream);Txing.Text=useEnglish?$"DISPLAY {which} SAVED":$"DISPLAY {which} LAGRET";
 }
 void MonitorClick(object s,RoutedEventArgs e){start();Txing.Text=useEnglish?"MONITOR ON":"MONITOR PÅ";}void StopMonitorClick(object s,RoutedEventArgs e){stop();Txing.Text=useEnglish?"MONITOR OFF":"MONITOR AV";}void DecodeClick(object s,RoutedEventArgs e){start();}void ClearClick(object s,RoutedEventArgs e){clear();rx.Clear();}void ClearRxClick(object s,RoutedEventArgs e)=>rx.Clear();void HaltClick(object s,RoutedEventArgs e){stop();DxCall.Clear();DxGrid.Clear();Txing.Text=useEnglish?"QSO RESET":"QSO AVSLUTTET";}void StopTxClick(object s,RoutedEventArgs e){Arm.IsChecked=false;autoArm(AutoNext.IsChecked==true,false);Txing.Text=useEnglish?"TX STOPPED":"TX STOPPET";}void TuneClick(object s,RoutedEventArgs e)=>MessageBox.Show(useEnglish?"Tune requires a completed CAT/PTT driver and is safety locked.":"Tune krever ferdig CAT/PTT-driver og er sikkerhetssperret.","FT8 Tune");
 void GenerateClick(object s,RoutedEventArgs e){TxList.Items.Clear();string me=StationCall.Text.Trim().ToUpper(),dx=DxCall.Text.Trim().ToUpper(),g=StationGrid.Text.Trim().ToUpper(),r=Report.Text.Trim();foreach(var m in new[]{$"CQ {me} {g}",$"{dx} {me} {g}",$"{dx} {me} {r}",$"{dx} {me} R{r}",$"{dx} {me} RRR",$"{dx} {me} 73"}){var call=m.StartsWith("CQ ",StringComparison.OrdinalIgnoreCase)?me:dx;TxList.Items.Add(new TxQueueRow(call,"—",TxHz.Text,m));}TxList.SelectedIndex=0;QueueTab.Header=useEnglish?$"Queue {TxList.Items.Count}":$"Kø {TxList.Items.Count}";}void AutoClick(object s,RoutedEventArgs e){AutoNext.IsChecked=!(AutoNext.IsChecked==true);AutoButton.Content=AutoNext.IsChecked==true?(useEnglish?"AUTO IS ON":"AUTO ER PÅ"):(useEnglish?"AUTO IS OFF":"AUTO ER AV");autoArm(AutoNext.IsChecked==true,Arm.IsChecked==true);}void SendSelectedClick(object s,RoutedEventArgs e){autoArm(AutoNext.IsChecked==true,Arm.IsChecked==true);var message=TxList.SelectedItem is TxQueueRow row?row.Message:TxList.SelectedItem?.ToString()??"";Txing.Text=Arm.IsChecked==true?$"TXing: {message}":(useEnglish?"TX LOCKED • arm transmit":"TX SPERRET • armer sending");}
}
