using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Media.Imaging;
using Microsoft.Win32;

namespace RadioLog;
public partial class MainWindow : Window
{
 readonly Storage store = new(); readonly Ft8Engine engine = new(); readonly ActivationFeeds feeds = new(); readonly LogSyncService sync = new(); readonly ObservableCollection<Qso> log; readonly ObservableCollection<Ft8Signal> decoded = []; readonly ObservableCollection<Activation> points; readonly List<Activation> livePoints = []; readonly Settings settings;
 Activation? selectedPoint;
 static string L(string norwegian,string english)=>Ft8AdvancedPanel.EnglishActive?english:norwegian;
 public MainWindow()
 {
  InitializeComponent(); AddCallsignCredit(this); settings = store.LoadSettings(); MyCall.Text = settings.MyCall; MyGrid.Text = settings.MyGrid;
  AutoUploadCheck.IsChecked=settings.AutoUpload;QrzCheck.IsChecked=settings.SyncQrz;QrzKey.Text=settings.QrzApiKey;CloudlogCheck.IsChecked=settings.SyncCloudlog;CloudlogUrl.Text=settings.CloudlogUrl;CloudlogKey.Text=settings.CloudlogApiKey;CloudlogStation.Text=settings.CloudlogStationId.ToString();UdpCheck.IsChecked=settings.SyncUdp;UdpPort.Text=settings.SyncUdpPort.ToString();ClubLogCheck.IsChecked=settings.SyncClubLog;ClubLogEmail.Text=settings.ClubLogEmail;ClubLogPassword.Password=settings.ClubLogPassword;HrdLogCheck.IsChecked=settings.SyncHrdLog;HrdLogCall.Text=settings.HrdLogCall;HrdLogCode.Password=settings.HrdLogCode;EqslCheck.IsChecked=settings.SyncEqsl;EqslUser.Text=settings.EqslUser;EqslPassword.Password=settings.EqslPassword;HamQthCheck.IsChecked=settings.SyncHamQth;HamQthUser.Text=settings.HamQthUser;HamQthPassword.Password=settings.HamQthPassword;LotwCheck.IsChecked=settings.SyncLotw;TqslPath.Text=settings.TqslPath;Log4OmCheck.IsChecked=settings.SyncLog4Om;N3fjpCheck.IsChecked=settings.SyncN3fjp;DxKeeperCheck.IsChecked=settings.SyncDxKeeper;HrdLocalCheck.IsChecked=settings.SyncHrdLocal;sync.Status+=s=>Dispatcher.Invoke(()=>{var message=TranslateSyncStatus(s);SyncStatus.Text=message;Footer.Text=message;});
  MapStyleChoice.Width=105;MapStyleChoice.Height=30;MapStyleChoice.MaxDropDownHeight=90;
  ShowPota.Background=new SolidColorBrush(Color.FromRgb(28,145,75));ShowPota.Foreground=Brushes.White;ShowBota.Background=new SolidColorBrush(Color.FromRgb(232,171,24));ShowBota.Foreground=new SolidColorBrush(Color.FromRgb(8,20,38));ShowSota.Background=new SolidColorBrush(Color.FromRgb(166,48,188));ShowSota.Foreground=Brushes.White;
  if(ShowSota.Parent is StackPanel layerPanel){var legend=new Border{Margin=new Thickness(5,3,5,10),Padding=new Thickness(8,6,8,6),CornerRadius=new CornerRadius(6),Background=new SolidColorBrush(Color.FromArgb(120,7,25,39)),BorderBrush=new SolidColorBrush(Color.FromRgb(38,78,100)),BorderThickness=new Thickness(1)};var row=new StackPanel{Orientation=Orientation.Horizontal};var ring=new Ellipse{Width=18,Height=18,Stroke=new SolidColorBrush(Color.FromRgb(54,242,139)),StrokeThickness=3,Fill=Brushes.Transparent,Margin=new Thickness(0,0,8,0),Effect=new System.Windows.Media.Effects.DropShadowEffect{Color=Color.FromRgb(49,239,131),BlurRadius=8,ShadowDepth=0,Opacity=.7}};row.Children.Add(ring);row.Children.Add(new TextBlock{Text="Grønn ring rundt punkt = aktivt nå",Foreground=new SolidColorBrush(Color.FromRgb(190,255,218)),VerticalAlignment=VerticalAlignment.Center,FontSize=11,FontWeight=FontWeights.SemiBold});legend.Child=row;int pos=layerPanel.Children.IndexOf(ShowSota);layerPanel.Children.Insert(pos+1,legend);}
  log = new(store.LoadLog().OrderByDescending(x => x.TimeUtc)); points = new(store.LoadPoints()); LogGrid.ItemsSource = log; DecodeGrid.ItemsSource = decoded;
  Ft8AdvancedPanel? advanced=null;advanced=new Ft8AdvancedPanel(decoded,settings.MyCall,settings.MyGrid,()=>{MyCall.Text=advanced!.StationCall.Text.Trim().ToUpperInvariant();MyGrid.Text=advanced.StationGrid.Text.Trim().ToUpperInvariant();settings.DialFrequencyMhz=advanced.ManualFrequencyMhz;SaveSettings();engine.Start();},()=>engine.Stop(),()=>decoded.Clear(),(auto,armed)=>{engine.AutoEnabled=auto;engine.TransmitArmed=armed;AutoMode.IsChecked=auto;ArmTx.IsChecked=armed;});advanced.SetFrequency(settings.DialFrequencyMhz);advanced.NavigateRequested+=page=>MainTabs.SelectedIndex=page switch{"LYDKORT"=>4,"RADIO"=>5,"LOGGSYNK"=>6,"BRUKSANVISNING"=>7,_=>0};((TabItem)MainTabs.Items[0]).Content=advanced;bool catBusy=false;var catTimer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};catTimer.Tick+=async(_,_)=>{if(catBusy||advanced.AutoCatEnabled==false)return;catBusy=true;var mhz=await CatFrequencyReader.ReadAsync(settings);catBusy=false;if(mhz is >0){settings.DialFrequencyMhz=mhz.Value;advanced.SetFrequency(mhz.Value);Footer.Text=$"CAT: {mhz.Value:0.000000} MHz";}};catTimer.Start();
  RadioMaker.ItemsSource = RadioCatalog.Manufacturers; RadioMaker.SelectedItem = settings.RadioManufacturer;
  RadioPort.ItemsSource = Enumerable.Range(1,64).Select(i=>$"COM{i}"); RadioPort.SelectedItem = settings.Port;
  RadioBaud.ItemsSource = new[]{1200,2400,4800,9600,19200,38400,57600,115200}; RadioBaud.SelectedItem = settings.BaudRate;
  RefreshPttItems();
  DetectAudio(this,new RoutedEventArgs());
  MapView.MarkerSelected += p => Dispatcher.Invoke(()=>SelectPoint(p));
  GridTrackerMap.HomeMoved += (lat,lon) => Dispatcher.Invoke(()=>{var grid=Maidenhead.Encode(lat,lon,10);MyGrid.Text=grid;settings.MyGrid=grid;store.SaveSettings(settings);Footer.Text=Ft8AdvancedPanel.EnglishActive?$"New position saved: {grid} ({lat:F6}, {lon:F6})":$"Ny posisjon lagret: {grid} ({lat:F6}, {lon:F6})";});
  engine.Status += s => Dispatcher.Invoke(() => { var message=TranslateEngineStatus(s);EngineStatus.Text=message;Footer.Text=message; });
  engine.Decoded += d => Dispatcher.Invoke(() => { decoded.Insert(0, d); while (decoded.Count > 200) decoded.RemoveAt(decoded.Count - 1); });
  engine.Logged += q => Dispatcher.Invoke(() => { q.Program=((ComboBoxItem)ActiveOtaProgram.SelectedItem).Content?.ToString()??"";q.Reference=ActiveOtaRef.Text.Trim().ToUpperInvariant();AddQso(q); });
  MyGrid.TextChanged += (_,_) => CenterGridTracker();
  var timer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromSeconds(1) }; timer.Tick += (_,_) => Clock.Text = DateTime.Now.ToString("dd.MM.yyyy  HH:mm:ss"); timer.Start();var liveTimer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMinutes(1)};liveTimer.Tick+=(_,_)=>RefreshActivations(this,new RoutedEventArgs());liveTimer.Start(); Loaded += (_,_) => { UpdateMap(); CenterGridTracker(); DrawWaterfall(); RefreshActivations(this,new RoutedEventArgs()); }; Closing += (_,_) => { SaveSettings(); engine.Dispose(); };
 }
 void SaveSettings() { settings.MyCall = MyCall.Text.Trim().ToUpperInvariant(); settings.MyGrid = MyGrid.Text.Trim().ToUpperInvariant(); store.SaveSettings(settings); }
 static string TranslateEngineStatus(string value)
 {
  if(!Ft8AdvancedPanel.EnglishActive)return value;if(value=="Egen FT8-motor startet – mottak/sekvensering aktiv")return "HamNavigator FT8 engine started – receiving/sequencing active";if(value=="FT8-motor stoppet")return "FT8 engine stopped";if(value=="Lytter – ingen ledig CQ i kø")return "Listening – no available CQ in queue";if(value.StartsWith("TX ikke armert – klar melding: "))return value.Replace("TX ikke armert – klar melding: ","TX not armed – message ready: ");return value;
 }
 static string TranslateSyncStatus(string value)
 {
  if(!Ft8AdvancedPanel.EnglishActive)return value;return value.Replace("Autolasting er på, men ingen ferdig konfigurert tjeneste er valgt.","Automatic upload is enabled, but no fully configured service is selected.").Replace("QSO lastet opp","QSO uploaded").Replace("QSO sendt","QSO sent").Replace("Lokal UDP","Local UDP").Replace("sendt til","sent to").Replace("svar mottatt","response received").Replace("QRZ-feil","QRZ error").Replace("Cloudlog-feil","Cloudlog error").Replace("UDP-feil","UDP error").Replace("LoTW-feil","LoTW error").Replace("TQSL-programmet ble ikke funnet","TQSL program was not found").Replace("sendt gjennom TQSL","sent through TQSL").Replace("TQSL returnerte feil","TQSL returned an error").Replace("Skriv inn QRZ API-nøkkel","Enter the QRZ API key");
 }
 static void AddCallsignCredit(DependencyObject root){foreach(var item in LogicalTreeHelper.GetChildren(root)){if(item is TextBlock t&&t.Text.Contains("programmert av Stian Bjerkan",StringComparison.OrdinalIgnoreCase)&&!t.Text.Contains("LB7YK"))t.Text+=" • LB7YK";if(item is DependencyObject child)AddCallsignCredit(child);}}
 void CenterGridTracker(){if(GridTrackerMap==null)return;string grid=MyGrid.Text.Trim().ToUpperInvariant();if(Maidenhead.TryCenter(grid,out var lat,out var lon)){int z=grid.Length switch{4=>7,6=>10,8=>14,10=>18,_=>9};GridTrackerMap.SetView(lat,lon,z);GridTrackerMap.SetQsoData(log,grid);Footer.Text=Ft8AdvancedPanel.EnglishActive?$"GridTracker centered on {grid} ({lat:F6}, {lon:F6})":$"GridTracker sentrert på {grid} ({lat:F6}, {lon:F6})";}}
 void MakerChanged(object s, SelectionChangedEventArgs e) { if (RadioMaker.SelectedItem is not string maker) return; RadioModel.ItemsSource = RadioCatalog.All.Where(x=>x.Manufacturer==maker).Select(x=>x.Model); RadioModel.SelectedItem = settings.RadioManufacturer==maker ? settings.RadioModel : RadioModel.Items.Cast<string>().FirstOrDefault(); }
 void ModelChanged(object s, SelectionChangedEventArgs e) { var p=RadioCatalog.All.FirstOrDefault(x=>x.Manufacturer==(RadioMaker.SelectedItem as string) && x.Model==(RadioModel.SelectedItem as string)); ProtocolText.Text=p is null?"":Ft8AdvancedPanel.EnglishActive?$"Protocol: {p.Protocol}":$"Protokoll: {p.Protocol}"; }
 void RefreshPttItems(){string selected=(RadioPtt.SelectedItem as string)??settings.PttMethod;if(selected=="None")selected="Ingen";RadioPtt.ItemsSource=Ft8AdvancedPanel.EnglishActive?new[]{"CAT","RTS","DTR","VOX","None"}:new[]{"CAT","RTS","DTR","VOX","Ingen"};RadioPtt.SelectedItem=Ft8AdvancedPanel.EnglishActive&&selected=="Ingen"?"None":selected;}
 void SaveRadio(object s, RoutedEventArgs e) { settings.RadioManufacturer=RadioMaker.SelectedItem as string ?? "Custom"; settings.RadioModel=RadioModel.SelectedItem as string ?? "User-defined CAT"; settings.Port=RadioPort.SelectedItem as string ?? "COM1"; settings.BaudRate=RadioBaud.SelectedItem is int b?b:19200; var ptt=RadioPtt.SelectedItem as string ?? "CAT";settings.PttMethod=ptt=="None"?"Ingen":ptt; store.SaveSettings(settings); Footer.Text=Ft8AdvancedPanel.EnglishActive?$"Saved {settings.RadioManufacturer} {settings.RadioModel}":$"Lagret {settings.RadioManufacturer} {settings.RadioModel}"; }
 void TestCat(object s, RoutedEventArgs e) { SaveRadio(s,e); MessageBox.Show(L("CAT-driveren for denne protokollfamilien er ikke aktivert ennå. Ingen kommando ble sendt til radioen.","The CAT driver for this protocol family has not been enabled yet. No command was sent to the radio."),L("CAT-test","CAT test")); }
 void TestPtt(object s, RoutedEventArgs e) { MessageBox.Show(L("PTT-test er sperret til CAT-driver og sikker tidsavbrudd er implementert.","PTT testing is locked until the CAT driver and a safety timeout have been implemented."),L("PTT-test","PTT test")); }
 void GtHome(object s,RoutedEventArgs e)=>CenterGridTracker();
 void GtWorld(object s,RoutedEventArgs e){GridTrackerMap.SetView(20,0,2);GtStatus.Text=L("Verdensvisning","World view");}
 void GtGrid(object s,RoutedEventArgs e)=>GtStatus.Text=GridTrackerMap.ToggleGrid()?L("Maidenhead-rutenett på","Maidenhead grid on"):L("Maidenhead-rutenett av","Maidenhead grid off");
 void GtPaths(object s,RoutedEventArgs e)=>GtStatus.Text=GridTrackerMap.TogglePaths()?L("QSO-linjer på","QSO paths on"):L("QSO-linjer av","QSO paths off");
 void GtLog(object s,RoutedEventArgs e)=>MainTabs.SelectedIndex=1;
 void GtOta(object s,RoutedEventArgs e)=>MainTabs.SelectedIndex=2;
 void GtAudio(object s,RoutedEventArgs e)=>MainTabs.SelectedIndex=4;
 void GtStats(object s,RoutedEventArgs e){int grids=log.Select(q=>q.Grid).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Count();int calls=log.Select(q=>q.Call).Distinct(StringComparer.OrdinalIgnoreCase).Count();GtStatus.Text=Ft8AdvancedPanel.EnglishActive?$"{log.Count:N0} QSO • {calls:N0} call signs • {grids:N0} locators":$"{log.Count:N0} QSO • {calls:N0} kallesignal • {grids:N0} locatorer";}
 void GtHelp(object s,RoutedEventArgs e)=>MessageBox.Show(L("QTH sentrerer kartet. Verden zoomer ut. Rutenett og QSO-linjer kan slås av/på. Dra den røde markøren for å lagre en presis 10-tegns locator.","QTH centres the map. World zooms out. The grid and QSO paths can be toggled. Drag the red marker to save an exact 10-character locator."),L("GridTracker-hjelp","GridTracker help"));
 void GtFindCall(object s,RoutedEventArgs e){string call=GtCallSearch.Text.Trim();var q=log.FirstOrDefault(x=>x.Call.Equals(call,StringComparison.OrdinalIgnoreCase)&&Maidenhead.TryCenter(x.Grid,out _,out _));if(q==null){GtStatus.Text=L("Kallesignal med locator ikke funnet i loggen","Call sign with locator not found in log");return;}Maidenhead.TryCenter(q.Grid,out var lat,out var lon);GridTrackerMap.SetView(lat,lon,10);GtStatus.Text=$"{q.Call} • {q.Grid} • {q.Band} {q.Mode}";}
 void DetectAudio(object s,RoutedEventArgs e)
 {
  var inputs=AudioDevices.Inputs();var outputs=AudioDevices.Outputs();AudioInput.ItemsSource=inputs;AudioOutput.ItemsSource=outputs;
  AudioInput.SelectedItem=inputs.FirstOrDefault(x=>x.Id==settings.AudioInputId)??AudioDevices.Best(inputs);AudioOutput.SelectedItem=outputs.FirstOrDefault(x=>x.Id==settings.AudioOutputId)??AudioDevices.Best(outputs);
  SetDetectedAudioStatus(inputs.Count,outputs.Count);if(settings.AudioInputId<0||settings.AudioOutputId<0)SaveAudio(s,e);
 }
 void SetDetectedAudioStatus(int inputCount,int outputCount){var ai=AudioInput.SelectedItem as AudioDevice;var ao=AudioOutput.SelectedItem as AudioDevice;AudioStatus.Text=Ft8AdvancedPanel.EnglishActive?$"Found {inputCount} inputs and {outputCount} outputs.\nAutomatic RX: {ai?.DisplayName??"none"}\nAutomatic TX: {ao?.DisplayName??"none"}":$"Fant {inputCount} innganger og {outputCount} utganger.\nAutomatisk RX: {ai?.DisplayName??"ingen"}\nAutomatisk TX: {ao?.DisplayName??"ingen"}";AudioInput.Items.Refresh();AudioOutput.Items.Refresh();}
 void SaveAudio(object s,RoutedEventArgs e)
 {
  if(AudioInput.SelectedItem is AudioDevice ai)settings.AudioInputId=ai.Id;if(AudioOutput.SelectedItem is AudioDevice ao)settings.AudioOutputId=ao.Id;store.SaveSettings(settings);AudioStatus.Text=Ft8AdvancedPanel.EnglishActive?$"FT8 sound selection saved. RX: {(AudioInput.SelectedItem as AudioDevice)?.DisplayName}. TX: {(AudioOutput.SelectedItem as AudioDevice)?.DisplayName}.":$"FT8 lydvalg lagret. RX: {(AudioInput.SelectedItem as AudioDevice)?.DisplayName}. TX: {(AudioOutput.SelectedItem as AudioDevice)?.DisplayName}.";
 }
 void ClearDecodes(object s, RoutedEventArgs e) => decoded.Clear();
 void WaterfallSizeChanged(object s, SizeChangedEventArgs e) => DrawWaterfall();
 void DrawWaterfall()
 {
  if (WaterfallImage==null || WaterfallOverlay==null) return; int w=Math.Max(1,(int)WaterfallOverlay.ActualWidth), h=Math.Max(1,(int)WaterfallOverlay.ActualHeight); if(w<10||h<10)return;
  var pixels=new byte[w*h*4]; for(int y=0;y<h;y++) for(int x=0;x<w;x++){int i=(y*w+x)*4; byte v=(byte)(6+18*(h-y)/h); pixels[i]=v;pixels[i+1]=(byte)(v+7);pixels[i+2]=(byte)(v+14);pixels[i+3]=255;}
  var bmp=new WriteableBitmap(w,h,96,96,PixelFormats.Bgra32,null);bmp.WritePixels(new Int32Rect(0,0,w,h),pixels,w*4,0);WaterfallImage.Source=bmp;WaterfallOverlay.Children.Clear();
  for(int hz=0;hz<=3000;hz+=500){double x=hz/3000d*w;WaterfallOverlay.Children.Add(new Line{X1=x,X2=x,Y1=0,Y2=h,Stroke=new SolidColorBrush(Color.FromArgb(70,148,163,184))});var t=new TextBlock{Text=$"{hz} Hz",Foreground=Brushes.LightGray,FontSize=11};Canvas.SetLeft(t,Math.Min(x+3,w-50));Canvas.SetTop(t,3);WaterfallOverlay.Children.Add(t);}
 }
 void StartEngine(object s, RoutedEventArgs e) { SaveSettings(); engine.Start(); }
 void StopEngine(object s, RoutedEventArgs e) => engine.Stop();
 void AutoChanged(object s, RoutedEventArgs e) => engine.AutoEnabled = AutoMode.IsChecked == true;
 void ArmChanged(object s, RoutedEventArgs e) => engine.TransmitArmed = ArmTx.IsChecked == true;
 void AddManual(object s, RoutedEventArgs e)
 {
  var call = CallInput.Text.Trim().ToUpperInvariant(); if (call.Length < 3) { MessageBox.Show(L("Skriv inn et gyldig kallesignal.","Enter a valid call sign.")); return; }
  string selectedProgram=((ComboBoxItem)ProgramInput.SelectedItem).Content?.ToString()??"Vanlig QSO";bool normalQso=selectedProgram is "Vanlig QSO" or "Normal QSO";double.TryParse(FrequencyInput.Text.Replace(',','.'),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var mhz);AddQso(new Qso { Call = call, Mode = ((ComboBoxItem)ModeInput.SelectedItem).Content.ToString()!, Band = ((ComboBoxItem)BandInput.SelectedItem).Content.ToString()!, FrequencyMhz=mhz,RstSent = RstInput.Text, RstReceived = RstInput.Text, Grid = GridInput.Text.Trim().ToUpperInvariant(), Program = normalQso?"":selectedProgram, Reference = normalQso?"":RefInput.Text.Trim().ToUpperInvariant(),Notes=QsoNotesInput.Text.Trim() }); CallInput.Clear();QsoNotesInput.Clear();
 }
 void AddQso(Qso q) { log.Insert(0, q); store.SaveLog(log); UpdateActivatedMap(); Footer.Text = Ft8AdvancedPanel.EnglishActive?$"Logged {q.Call} on {q.Mode}":$"Logget {q.Call} på {q.Mode}"; SaveSyncSettings(); _=sync.UploadAsync(q,settings); }
 void SaveSyncSettings(){settings.AutoUpload=AutoUploadCheck.IsChecked==true;settings.SyncQrz=QrzCheck.IsChecked==true;settings.QrzApiKey=QrzKey.Text.Trim();settings.SyncCloudlog=CloudlogCheck.IsChecked==true;settings.CloudlogUrl=CloudlogUrl.Text.Trim();settings.CloudlogApiKey=CloudlogKey.Text.Trim();settings.CloudlogStationId=int.TryParse(CloudlogStation.Text,out var sid)?sid:1;settings.SyncUdp=UdpCheck.IsChecked==true;settings.SyncUdpPort=int.TryParse(UdpPort.Text,out var port)?Math.Clamp(port,1,65535):2333;settings.SyncClubLog=ClubLogCheck.IsChecked==true;settings.ClubLogEmail=ClubLogEmail.Text.Trim();settings.ClubLogPassword=ClubLogPassword.Password;settings.SyncHrdLog=HrdLogCheck.IsChecked==true;settings.HrdLogCall=HrdLogCall.Text.Trim();settings.HrdLogCode=HrdLogCode.Password;settings.SyncEqsl=EqslCheck.IsChecked==true;settings.EqslUser=EqslUser.Text.Trim();settings.EqslPassword=EqslPassword.Password;settings.SyncHamQth=HamQthCheck.IsChecked==true;settings.HamQthUser=HamQthUser.Text.Trim();settings.HamQthPassword=HamQthPassword.Password;settings.SyncLotw=LotwCheck.IsChecked==true;settings.TqslPath=TqslPath.Text.Trim();settings.SyncLog4Om=Log4OmCheck.IsChecked==true;settings.SyncN3fjp=N3fjpCheck.IsChecked==true;settings.SyncDxKeeper=DxKeeperCheck.IsChecked==true;settings.SyncHrdLocal=HrdLocalCheck.IsChecked==true;store.SaveSettings(settings);SyncStatus.Text=Ft8AdvancedPanel.EnglishActive?"Synchronization settings saved.":"Synkroniseringsoppsett lagret.";}
 void SaveSync(object s,RoutedEventArgs e){SaveSyncSettings();if(Ft8AdvancedPanel.EnglishActive)SyncStatus.Text="Synchronization settings saved.";}
 async void TestQrzSync(object s,RoutedEventArgs e){SaveSyncSettings();SyncStatus.Text=L("Tester QRZ …","Testing QRZ…");SyncStatus.Text=TranslateSyncStatus(await sync.TestQrz(settings.QrzApiKey));}
 async void TestCloudlogSync(object s,RoutedEventArgs e){SaveSyncSettings();SyncStatus.Text=L("Tester Cloudlog/Wavelog …","Testing Cloudlog/Wavelog…");SyncStatus.Text=await sync.TestCloudlog(settings);}
 async void TestLogService(object s,RoutedEventArgs e){SaveSyncSettings();string name=(s as Button)?.Tag?.ToString()??"";SyncStatus.Text=Ft8AdvancedPanel.EnglishActive?$"Testing {name}…":$"Tester {name} …";string result=await sync.TestService(name,settings);SyncStatus.Text=Ft8AdvancedPanel.EnglishActive?result:TranslateServiceTest(result);}
 static string TranslateServiceTest(string value)=>value.Replace("missing e-mail/password.","mangler e-post/passord.").Replace("missing call sign/upload code.","mangler kallesignal/opplastingskode.").Replace("missing username/password.","mangler brukernavn/passord.").Replace("connection and required fields test passed.","tilkobling og obligatoriske felt er godkjent.").Replace("Local UDP test sent to","Lokal UDP-test sendt til").Replace("tqsl.exe was not found at the selected path.","tqsl.exe ble ikke funnet på valgt filsti.").Replace("TQSL installation test passed.","TQSL-installasjonstesten er godkjent.").Replace("could not be started.","kunne ikke startes.").Replace("server responded HTTP","serveren svarte HTTP").Replace("test error:","testfeil:").Replace("Enter the","Skriv inn").Replace("API settings are present.","API-innstillingene finnes.").Replace("server connection passed","servertilkoblingen er godkjent");
 void ExportAdif(object s, RoutedEventArgs e) { var d = new SaveFileDialog { Filter = "ADIF (*.adi)|*.adi", FileName = "hamnavigator.adi" }; if (d.ShowDialog() == true) { store.ExportAdif(d.FileName, log); Footer.Text = L("Eksportert ","Exported ") + d.FileName; } }
 void AddPoint(object s, RoutedEventArgs e)
 {
  if (!double.TryParse(MapLat.Text.Replace(',', '.'), System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var lat) || !double.TryParse(MapLon.Text.Replace(',', '.'), System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var lon)) { MessageBox.Show(L("Bredde- og lengdegrad må være tall.","Latitude and longitude must be numbers.")); return; }
  string program=((ComboBoxItem)MapProgram.SelectedItem).Content.ToString()!, reference=MapRef.Text.Trim().ToUpperInvariant();var local=points.FirstOrDefault(x=>x.Program==program&&x.Reference.Equals(reference,StringComparison.OrdinalIgnoreCase));if(local==null){local=new Activation();points.Add(local);}local.Program=program;local.Reference=reference;local.Name=MapName.Text.Trim();local.Latitude=lat;local.Longitude=lon;local.Notes=MapNotes.Text.Trim();selectedPoint=local;store.SavePoints(points);UpdateMap();MapView.SetView(lat,lon,Math.Max(12,MapView.Zoom));Footer.Text=Ft8AdvancedPanel.EnglishActive?$"Saved information for {program} {reference}":$"Lagret informasjon for {program} {reference}";
 }
 void SelectPoint(Activation p){selectedPoint=p;MapRef.Text=p.Reference;MapName.Text=p.Name;MapLat.Text=p.Latitude.ToString("0.######",System.Globalization.CultureInfo.InvariantCulture);MapLon.Text=p.Longitude.ToString("0.######",System.Globalization.CultureInfo.InvariantCulture);MapNotes.Text=points.FirstOrDefault(x=>x.Program==p.Program&&x.Reference==p.Reference)?.Notes??p.Notes;foreach(ComboBoxItem i in MapProgram.Items)if((i.Content?.ToString()??"")==p.Program){MapProgram.SelectedItem=i;break;}Footer.Text=Ft8AdvancedPanel.EnglishActive?$"Selected {p.Program} {p.Reference}":$"Valgt {p.Program} {p.Reference}";}
 void NewPoint(object s,RoutedEventArgs e){selectedPoint=null;MapRef.Clear();MapName.Clear();MapLat.Clear();MapLon.Clear();MapNotes.Clear();Footer.Text=L("Nytt kartpunkt","New map point");}
 void MapFilter(object s, RoutedEventArgs e) => UpdateMap();
 void MapStyleChanged(object s,SelectionChangedEventArgs e){if(MapView==null||GridTrackerMap==null)return;string choice=(MapStyleChoice.SelectedItem as ComboBoxItem)?.Content?.ToString()??"";bool sat=choice is "Satellitt" or "Satellite";MapView.UseSatellite(sat);GridTrackerMap.UseSatellite(sat);Footer.Text=Ft8AdvancedPanel.EnglishActive?(sat?"Satellite map selected":"Street map selected"):(sat?"Satellittkart valgt":"Gatekart valgt");}
 public void RefreshDynamicLanguage()
 {
  SetDetectedAudioStatus(AudioInput.Items.Count,AudioOutput.Items.Count);RefreshPttItems();var radio=RadioCatalog.All.FirstOrDefault(x=>x.Manufacturer==(RadioMaker.SelectedItem as string)&&x.Model==(RadioModel.SelectedItem as string));if(radio is not null)ProtocolText.Text=Ft8AdvancedPanel.EnglishActive?$"Protocol: {radio.Protocol}":$"Protokoll: {radio.Protocol}";if(livePoints.Count==0){FeedStatus.Text=Ft8AdvancedPanel.EnglishActive?"Not updated":"Ikke oppdatert";return;}int pota=livePoints.Count(x=>x.Program=="POTA"),sota=livePoints.Count(x=>x.Program=="SOTA"),bota=livePoints.Count(x=>x.Program=="BOTA"),spots=livePoints.Count(x=>x.ActivityType=="LIVE SPOT"),alerts=livePoints.Count(x=>x.ActivityType=="ALERT");FeedStatus.Text=Ft8AdvancedPanel.EnglishActive?$"Updated: POTA {pota:N0} • SOTA {sota:N0} • BOTA {bota:N0}\nSOTLAS live: {spots} spots • {alerts} alerts • automatic every minute.":$"Oppdatert: POTA {pota:N0} • SOTA {sota:N0} • BOTA {bota:N0}\nSOTLAS-live: {spots} spots • {alerts} varsler • automatisk hvert minutt.";
 }
 async void RefreshActivations(object s,RoutedEventArgs e)
 {
  FeedStatus.Text=L("Henter kataloger og SOTLAS-liveaktivitet …","Loading catalogues and SOTLAS live activity…");try{var fresh=await feeds.RefreshAsync();livePoints.Clear();livePoints.AddRange(fresh);UpdateMap();int pota=fresh.Count(x=>x.Program=="POTA"),sota=fresh.Count(x=>x.Program=="SOTA"),bota=fresh.Count(x=>x.Program=="BOTA"),spots=fresh.Count(x=>x.ActivityType=="LIVE SPOT"),alerts=fresh.Count(x=>x.ActivityType=="ALERT");FeedStatus.Text=Ft8AdvancedPanel.EnglishActive?$"Updated {DateTime.Now:HH:mm}: POTA {pota:N0} • SOTA {sota:N0} • BOTA {bota:N0}\nSOTLAS live: {spots} spots • {alerts} alerts • automatic every minute.":$"Oppdatert {DateTime.Now:HH:mm}: POTA {pota:N0} • SOTA {sota:N0} • BOTA {bota:N0}\nSOTLAS-live: {spots} spots • {alerts} alerts • automatisk hvert minutt.";}catch(Exception ex){FeedStatus.Text=L("Oppdatering feilet: ","Update failed: ")+ex.Message;}
 }
 void UpdateMap()
 {
  if(MapView==null)return;bool Enabled(string p)=>p switch{"POTA"=>ShowPota?.IsChecked==true,"BOTA"=>ShowBota?.IsChecked==true,"SOTA"=>ShowSota?.IsChecked==true,_=>false};var merged=points.Concat(livePoints).Where(x=>Enabled(x.Program)).GroupBy(x=>$"{x.Program}|{x.Reference}").Select(g=>g.First());MapView.SetMarkers(merged);GridTrackerMap?.SetQsoData(log,MyGrid.Text);UpdateActivatedMap();
 }
 void UpdateActivatedMap()
 {
  if(MapView==null)return;int Need(string p)=>p switch{"POTA"=>10,"SOTA"=>4,"BOTA"=>1,_=>int.MaxValue};var done=log.Where(q=>!string.IsNullOrWhiteSpace(q.Program)&&!string.IsNullOrWhiteSpace(q.Reference)).GroupBy(q=>$"{q.Program.ToUpperInvariant()}|{q.Reference.ToUpperInvariant()}").Where(g=>g.Count()>=Need(g.First().Program.ToUpperInvariant())).Select(g=>g.Key);MapView.SetActivated(done);
 }
}
