'use strict';
(() => {
  pageNames.cloud="Account and Cloud";
  const nav=document.querySelector('nav'),navButton=document.createElement('button');navButton.dataset.page='cloud';navButton.textContent="☁ Account and Cloud";nav.append(navButton);
  const accountButton=document.createElement('button');accountButton.className='secondary';accountButton.id='cloud-account-button';accountButton.textContent="Log in";document.querySelector('.header-actions').append(accountButton);
  const section=document.createElement('section');section.id='page-cloud';section.className='page';
  section.innerHTML=`<style>
  #page-cloud [hidden]{display:none!important} #page-cloud .account-tabs{display:flex;gap:8px;margin:16px 0 24px}
  #page-cloud .account-tabs button[aria-pressed="true"]{background:#9ce4d1;color:#102033} #page-cloud .account-form{max-width:760px}
  #page-cloud .account-form label{display:block;margin:14px 0} #page-cloud .account-form input:not([type="checkbox"]){width:100%;margin-top:7px}
  #page-cloud .account-form small{display:block;margin-top:6px} #page-cloud .password-row{display:flex;gap:8px;align-items:center}
  #page-cloud .password-row input{flex:1;min-width:0} #page-cloud .account-status{border-left:3px solid #9ce4d1;padding:12px 16px;background:#152634;overflow-wrap:anywhere}
  #page-cloud .account-status.error{border-color:#ff9e9e;color:#ffd0d0} #page-cloud .server-setup{margin:20px 0;border:1px solid #30485a;border-radius:8px;padding:16px}
  #page-cloud .server-setup summary{cursor:pointer;font-weight:600} #page-cloud .account-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}
  </style>
  <div class="page-heading"><div><p class="eyebrow">ONE ACCOUNT FOR YOUR RADIO DAY</p><h1>Your HamNavigator account</h1><p>Create an account or log in. HamNavigator connects you to Cloud automatically.</p></div></div>
  <article class="card" id="cloud-auth-card"><div class="account-tabs" aria-label="Login or registration"><button type="button" id="cloud-login-tab" class="secondary" aria-pressed="true">Log in</button><button type="button" id="cloud-register-tab" class="secondary" aria-pressed="false">Create account</button></div>
  <form id="cloud-connect" class="account-form"><h2 id="cloud-auth-title">Welcome back</h2><p id="cloud-auth-intro">Use the same account on your devices.</p>
  <details class="server-setup" id="cloud-server-setup"><summary>Advanced: own server</summary><p>Only needed if you use another private Cloud server.</p><button type="button" id="cloud-standard" class="secondary">Use HamNavigator Cloud</button>
  <button type="button" class="secondary" id="cloud-import">Open connection file</button><input type="file" id="cloud-connection-file" accept=".hamcloud" hidden>
  <label>Server address<input name="url" type="url" required placeholder="https://servername:9443"></label><label>Certificate file on this PC<input name="certificate" placeholder="Filled from the connection file"><small>HamNavigator Cloud does not need a certificate file.</small></label>
  <button type="button" class="secondary" id="cloud-check">Check connection</button><p id="cloud-connection-status" role="status"></p></details>
  <label>Email<input name="email" type="email" required maxlength="232" autocomplete="username"></label>
  <label for="cloud-password">Password</label><div class="password-row"><input id="cloud-password" name="password" type="password" required maxlength="256" aria-describedby="cloud-password-help" autocomplete="current-password"><button type="button" class="secondary" id="cloud-show-password" aria-pressed="false">Show</button></div><small id="cloud-password-help"></small>
  <label id="cloud-confirm-label" hidden>Repeat password<input name="password_confirm" type="password" maxlength="256" autocomplete="new-password" disabled></label>
  <div id="cloud-verify-group" hidden><label>Code from the email<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{8}" maxlength="8" placeholder="8 digits"></label><button type="button" id="cloud-resend" class="secondary">Send new code</button><p class="small muted">The code is valid for 15 minutes. Also check your spam folder.</p></div><label id="cloud-invite-label" hidden>Invitation code<input name="invite" autocomplete="off" disabled></label>
  <details id="cloud-recovery-details"><summary>Recovery after a password change</summary><label>Recovery key<input name="recovery" type="password" autocomplete="off" placeholder="Only needed if the key is not on this PC"></label></details>
  <p id="cloud-register-info" class="small muted" hidden>You will receive a one-time code by email to verify your account. You choose when to synchronize your logbook and settings. The server owner can see your account email, app version and last connection to display active users. No history of past activity is stored.</p>
  <div class="account-actions"><button class="primary" id="cloud-submit">Log in</button><button type="button" class="text-button" id="cloud-forgot">Forgot password?</button></div></form></article>
  <article class="card" id="cloud-reset-card" hidden><h2>Forgot password</h2><p>Receive a one-time code at your account email address and choose a new password.</p><form id="cloud-reset-form" class="account-form">
    <label>Email<input name="reset_email" type="email" required maxlength="232" autocomplete="username"></label><button type="button" id="cloud-reset-send" class="secondary">Send code by email</button>
    <label>Code from the email<input name="reset_code" required pattern="[0-9]{8}" inputmode="numeric" autocomplete="one-time-code" maxlength="8"></label>
    <label>New password<input name="reset_password" type="password" required minlength="12" maxlength="256" autocomplete="new-password"><small>At least 12 and no more than 256 characters.</small></label>
    <label>Repeat new password<input name="reset_confirm" type="password" required minlength="12" maxlength="256" autocomplete="new-password"></label>
    <p class="small muted">On a new PC, your recovery key may be needed to unlock encrypted settings after a password change. Old settings and contacts are kept.</p>
    <div class="account-actions"><button class="primary">Save new password</button><button type="button" id="cloud-reset-cancel" class="secondary">Back to login</button></div></form></article>
  <p id="cloud-auth-status" class="account-status" role="status" aria-live="polite">Log in or create an account to use HamNavigator. Downloads are free and public.</p>
  <article class="card" id="cloud-account-card" hidden><p class="eyebrow">YOUR ACCOUNT</p><h2 id="cloud-account-email"></h2><p id="cloud-account-server"></p><button id="cloud-retry" class="secondary">Verify login</button> <button id="cloud-out" class="secondary">Log out</button> <button id="cloud-recovery" class="secondary">Save recovery key</button><p class="small muted">The key restores encrypted settings if you forget your account password. Keep it private. Logging out keeps contacts on this PC.</p></article>
  <article class="card"><h2>Synchronization</h2><p id="cloud-status" role="status" aria-live="polite">Log in to synchronize.</p><label><input id="cloud-auto" type="checkbox" disabled> Automatic synchronization every 10 seconds</label><p><button id="cloud-now" class="primary" disabled>Synchronize now</button></p>
  <p class="small muted">Digital and MY SHACK use the shared hamnavigator.adi log. Contacts are shared both ways. Digital, Map and MY SHACK settings, passwords and API keys are stored encrypted in Cloud. Received program settings apply at the next startup. Active radio transmission is not resumed.</p>
  <p id="cloud-backup" class="small muted"></p><div id="cloud-conflicts"></div></article>
  <article class="card"><h2>Delivery to logging services</h2><p>Cloud shares delivery status from the Android app with your PCs.</p><button id="cloud-deliveries" class="secondary" disabled>Get delivery status</button><div id="cloud-delivery-list" role="status"></div></article>`;
  const main=document.querySelector('main');main.insertBefore(section,main.querySelector('footer'));
  const $=selector=>section.querySelector(selector),form=$('#cloud-connect'),fields=form.elements;
  let pendingVerification=false,busy=false,register=false,registration='open',connected=false,lastSync='',initial=true,editingServer=false,lastState={automatic:false};
  function openAccount(){showPage('cloud');status();}navButton.onclick=openAccount;accountButton.onclick=openAccount;
  function message(text,error=false){$('#cloud-auth-status').textContent=text;$('#cloud-auth-status').classList.toggle('error',error);}
  function controls(){section.querySelectorAll('button,input').forEach(e=>e.disabled=busy);fields.code.disabled=busy||!pendingVerification;fields.code.required=pendingVerification;fields.password_confirm.disabled=busy||!register;fields.password_confirm.required=register;const invite=register&&registration==='invite';fields.invite.disabled=busy||!invite;fields.invite.required=invite;$('#cloud-invite-label').hidden=!invite;for(const id of ['#cloud-auto','#cloud-now','#cloud-deliveries','#cloud-out','#cloud-recovery'])$(id).disabled=busy||!connected;$('#cloud-submit').disabled=busy||(register&&registration==='closed');}
  function mode(value){pendingVerification=false;$('#cloud-verify-group').hidden=true;fields.code.value='';$('#cloud-reset-card').hidden=true;register=value;fields.password.value='';fields.password_confirm.value='';fields.password_confirm.setCustomValidity('');fields.invite.value='';fields.password.type='password';$('#cloud-show-password').textContent="Show";$('#cloud-show-password').setAttribute('aria-pressed','false');$('#cloud-login-tab').setAttribute('aria-pressed',String(!register));$('#cloud-register-tab').setAttribute('aria-pressed',String(register));$('#cloud-auth-title').textContent=register?"Create your HamNavigator account":"Welcome back";$('#cloud-submit').textContent=register?"Create account":"Log in";$('#cloud-confirm-label').hidden=!register;$('#cloud-register-info').hidden=!register;$('#cloud-forgot').hidden=register;fields.password.minLength=register?12:1;fields.password.autocomplete=register?'new-password':'current-password';$('#cloud-password-help').textContent=register?"At least 12 and no more than 256 characters. Use a separate password for HamNavigator.":"Use your HamNavigator account password.";controls();}
  function render(s){
  const previously=window.hnAuthorized===true;window.hnAuthorized=s.authorized===true;
  document.body.classList.toggle('hn-authorized',window.hnAuthorized);
  window.dispatchEvent(new CustomEvent('hamnavigator-cloud-state',{detail:{admin:s.admin===true,authorized:window.hnAuthorized}}));
  if(!window.hnAuthorized && location.hash!=='#language')showPage('cloud');
  else if(window.hnAuthorized&&!previously){refreshState(true).catch(()=>{});if(location.hash!=='#cloud'&&location.hash!=='#language')showPage('home');}
  $('#cloud-retry').hidden=window.hnAuthorized;
  lastState=s;connected=!!s.connected;$('#cloud-auth-card').hidden=connected;$('#cloud-account-card').hidden=!connected;accountButton.textContent=connected?"My account":"Log in";$('#cloud-account-email').textContent=s.email||'';$('#cloud-account-server').textContent=s.url||'';$('#cloud-status').textContent=s.message+(s.last_sync?" Last synchronization: "+s.last_sync:'');$('#cloud-auto').checked=!!s.automatic;$('#cloud-backup').textContent=s.backup_folder?"Local backups: "+s.backup_folder:'';
  if(initial){fields.url.value=s.url||'https://lb7yk.no/cloud';fields.email.value=s.email||'';fields.certificate.value=s.certificate||'';$('#cloud-server-setup').open=!fields.url.value;initial=false;}
  const deliveries=$('#cloud-delivery-list');deliveries.replaceChildren();for(const item of (s.deliveries||[]).slice(-200)){const p=document.createElement('p');p.textContent=[item.call,item.date,item.time,item.service,item.state,item.message].filter(Boolean).join(' · ');deliveries.append(p);}
  const list=$('#cloud-conflicts');list.replaceChildren();const conflicts=s.conflicts||[];let shown=0;
  const names={'panels/layout':"Panel layout",'setting/call':"Callsign",'setting/grid':"Station grid locator",'setting/modules':"Selected modules",'setting/preferences':"Program settings",'map/preferences':"Map settings",'digital/preferences':"Digital settings"};
  const showMore=()=>{list.querySelector('.cloud-more-conflicts')?.remove();for(const conflict of conflicts.slice(shown,shown+20)){
    const box=document.createElement('details'),title=document.createElement('summary'),q=conflict.local&&typeof conflict.local==='object'?conflict.local:conflict.cloud||{};
    const date=String(q.QSO_DATE||'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$3.$2.$1'),time=String(q.TIME_ON||'').replace(/^(\d{2})(\d{2})(\d{2})$/,'$1:$2:$3');
    title.textContent=conflict.key.startsWith('qso/')?[q.CALL||"Contact",date,time?"at "+time+' UTC':''].filter(Boolean).join(' · '):(names[conflict.key]||"Saved settings");box.append(title);
    if(conflict.fields?.length){const text=document.createElement('p');text.textContent="Different details: "+conflict.fields.join(', ');box.append(text);}
    const pre=document.createElement('pre');pre.style.whiteSpace='pre-wrap';pre.style.overflowWrap='anywhere';pre.textContent=JSON.stringify({denne_PC:conflict.local,skyen:conflict.cloud},null,2);box.append(pre);
    for(const [choice,label] of [['local',"Keep this PC's version"],['cloud',"Use the Cloud version"]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>send('sync',{choices:{[conflict.key]:choice}});box.append(b);}list.append(box);
  }shown=Math.min(shown+20,conflicts.length);if(shown<conflicts.length){const more=document.createElement('button');more.className='secondary cloud-more-conflicts';more.textContent="Show more ("+(conflicts.length-shown)+" remaining)";more.onclick=showMore;list.append(more);}};
  showMore();controls();}
  async function status(){if(busy)return;try{const r=await fetch('/api/cloud/status');if(!r.ok)throw Error();const s=await r.json();if(busy)return;render(s);if(s.last_sync&&s.last_sync!==lastSync){lastSync=s.last_sync;await refreshState();}}catch{if(!busy)$('#cloud-status').textContent="Cannot read Cloud status.";}}
  async function send(action,data){if(busy)return;busy=true;controls();message("Working …");try{const r=await fetch('/api/cloud/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Radio-Token':document.querySelector('meta[name="radio-token"]').content},body:JSON.stringify(data)});const s=await r.json();if(!r.ok)throw Error(s.error||"The operation failed.");
  if(s.verification_required){pendingVerification=true;$('#cloud-verify-group').hidden=false;$('#cloud-submit').textContent="Verify and log in";message(s.message);return true;}
  if(['request-reset','reset-password','resend-verification','verify-email'].includes(action)){message(s.message);}
  else if(action==='recovery'){const blob=new Blob([s.text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download="HamNavigator-recovery-key.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message("Recovery key downloaded. Keep it private.");}
  else if(action==='check'||action==='import-connection'){registration=s.registration;fields.url.value=s.url;fields.certificate.value=s.certificate;editingServer=false;const text=registration==='open'?"Connected. Select Create account or Log in.":registration==='invite'?"Connected. The server requires an invitation code.":"Registration is closed. You can still sign in.";$('#cloud-connection-status').textContent=text;message(text);$('#cloud-server-setup').open=false;}
  else{render(s);message(s.message);if(action==='sync')await refreshState(true);}if(action==='connect'&&s.connected){pendingVerification=false;fields.password.value='';fields.password_confirm.value='';fields.invite.value='';fields.recovery.value='';}return true;}catch(e){message(e.message,true);return false;}finally{busy=false;controls();}}
  form.addEventListener('submit',async e=>{e.preventDefault();fields.password_confirm.setCustomValidity(register&&fields.password.value!==fields.password_confirm.value?"The passwords do not match.":'');if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));data.register=register;if(register&&editingServer){message("Check the server connection before creating an account.",true);$('#cloud-server-setup').open=true;return;}if(pendingVerification){if(await send('verify-email',data)){mode(false);fields.password.value=data.password;fields.recovery.value=data.recovery||'';await send('connect',{...data,register:false});}}else await send('connect',data);});
  form.addEventListener('invalid',e=>{if(e.target.name==='url')$('#cloud-server-setup').open=true;},true);fields.password_confirm.oninput=fields.password.oninput=()=>fields.password_confirm.setCustomValidity('');
  for(const key of ['url','certificate'])fields[key].oninput=()=>{editingServer=true;$('#cloud-connection-status').textContent="Check the new server connection before registering.";registration='open';controls();};
  $('#cloud-login-tab').onclick=()=>mode(false);$('#cloud-register-tab').onclick=()=>mode(true);$('#cloud-show-password').onclick=e=>{const show=fields.password.type==='password';fields.password.type=show?'text':'password';e.target.textContent=show?"Hide":"Show";e.target.setAttribute('aria-pressed',String(show));};
  const resetForm=$('#cloud-reset-form'),reset=resetForm.elements;
  $('#cloud-forgot').onclick=()=>{resetForm.reset();reset.reset_email.value=fields.email.value;$('#cloud-reset-card').hidden=false;$('#cloud-reset-card').scrollIntoView({block:'start',behavior:'smooth'});message("Request a code for your email address. No access to the server program is needed.");};
  $('#cloud-reset-cancel').onclick=()=>{$('#cloud-reset-card').hidden=true;mode(false);};
  $('#cloud-reset-send').onclick=()=>{if(reset.reset_email.reportValidity())send('request-reset',{email:reset.reset_email.value,url:fields.url.value,certificate:fields.certificate.value});};
  reset.reset_confirm.oninput=reset.reset_password.oninput=()=>reset.reset_confirm.setCustomValidity('');
  resetForm.onsubmit=async e=>{e.preventDefault();reset.reset_confirm.setCustomValidity(reset.reset_password.value===reset.reset_confirm.value?'':"The passwords do not match.");if(!resetForm.reportValidity())return;const email=reset.reset_email.value,password=reset.reset_password.value;if(await send('reset-password',{email,password,code:reset.reset_code.value,url:fields.url.value,certificate:fields.certificate.value})){mode(false);fields.email.value=email;fields.password.value=password;resetForm.reset();message("Password changed. Press Log in.");form.scrollIntoView({block:'start'});}};
  $('#cloud-resend').onclick=()=>send('resend-verification',{email:fields.email.value,url:fields.url.value,certificate:fields.certificate.value});
  $('#cloud-standard').onclick=()=>{fields.url.value='https://lb7yk.no/cloud';fields.certificate.value='';editingServer=false;registration='open';$('#cloud-server-setup').open=false;message("HamNavigator Cloud selected. Log in or create an account.");};
  $('#cloud-retry').onclick=()=>send('verify',{});$('#cloud-now').onclick=()=>send('sync',{});$('#cloud-deliveries').onclick=()=>send('deliveries',{});$('#cloud-recovery').onclick=()=>send('recovery',{});$('#cloud-out').onclick=async()=>{if(await send('disconnect',{}))mode(false);};$('#cloud-auto').onchange=async e=>{if(!await send('auto',{enabled:e.target.checked}))e.target.checked=!!lastState.automatic;};$('#cloud-check').onclick=()=>send('check',{url:fields.url.value,certificate:fields.certificate.value});$('#cloud-import').onclick=()=>$('#cloud-connection-file').click();$('#cloud-connection-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>65536){message("The connection file is too large.",true);return;}await send('import-connection',{text:await f.text()});e.target.value='';};
  mode(false);status().then(()=>{if(connected)send('verify',{});});if(location.hash==='#cloud')showPage('cloud',false);setInterval(status,5000);
})();
